### ISSUE TITLE
 [frontend] Pin a Post

### ISSUE THREAD

**Issue by daita** [nextcloud/social#1013]
- display an option on Posts so that the user/author can 'Pin Post'
- (backend) store pinned post
- display Pinned Post on the main page of the account
- (backend) returns Pinned Post

**Comment by daita** [comment]
duplicate of #125

**Comment by violoncelloCH** [comment]
I guess it makes sense to copy those points over to #125 and close this one, right?

**Comment by jancborchardt** [comment]
Copied over the points of the original post into https://github.com/nextcloud/social/issues/125, with checkboxes, and that one is also labeled and milestoned. :)
