### ISSUE TITLE
using WebfingerManager

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/social#1016]
- fix #121 
- nextcloud/server#21817

WIP as it might be better to create a WellKnownManager that would manage 
- /.well-known/webfinger
- /.well-known/nodeinfo
- /.well-known/hostmeta

instead of just managing the first one

**Comment by daita** [comment]
Uncomment https://github.com/nextcloud/social/blob/master/lib/AppInfo/Application.php#L76 to enable the feature, once nextcloud/server#21817 is merged

**Comment by tacruc** [comment]
On nextcloud 21 I recive the .well-known/webfinger not correct.


```
curl https://domain.com/.well-known/webfinger?resource=acct:user@domain.com
{"message":"webfinger not supported"}
```

I was wounding if it is connected to this Issue here?

**Comment by daita** [comment]
not related, this will be fixed later this week !

**Comment by mashedkeyboard** [comment]
> On nextcloud 21 I recive the .well-known/webfinger not correct warning on the social page.
> 
> ```
> curl https://domain.com/.well-known/webfinger?resource=acct:user@domain.com
> {"message":"webfinger not supported"}
> ```
> 
> I was wounding if it is connected to this Issue here?

I'm still geting this issue on NC21 - @daita, do you know when that fix is planned for inclusion in a release?

**Comment by cClaude** [comment]
Getting ```{"message":"webfinger not supported"}``` as well on stable channel.

This message is not clear for me. I would like to know what is wrong in my configuration ?

**Comment by mashedkeyboard** [comment]
social seems to be completely incompatible with Nextcloud 21 until this is fixed, which is a shame :( any word on a fix, @ArtificialOwl? I can work on a PR if it would be helpful

**Comment by CarlSchwan** [comment]
This is done
