### ISSUE TITLE
cannot enable master branch

### ISSUE THREAD

**Issue by StCyr** [nextcloud/social#1037]
**Describe the bug**
cannot enable master branch

**To Reproduce**
0. cd /var/www/nextcloud/apps
1. git clone https://github.com/nextcloud/social
2. make dev-setup
3. make build-js
4. cd ../..
5. sudo -u www-data php occ app:enable social
6. PHP Fatal error:  Trait 'daita\MySmallPhpTools\Traits\TPathTools' not found in /var/www/nextcloud/apps/social/lib/Service/ConfigService.php on line 49

**Expected behavior**
master branch should be enablable.

**Comment by icewind1991** [comment]
this is caused by `daita/my-small-php-tools` being set to a git branch instead of a release of specific commit, iirc `composer update` fixed it for me.

The proper fix would be to pin the dependency to a specific version to ensure everybody has the same one (cc @daita)

**Comment by jancborchardt** [comment]
@daita could you look into fixing that so @StCyr can run Social again? :)

**Comment by daita** [comment]
master should be fixed now

**Comment by StCyr** [comment]
merci @daita
