### ISSUE TITLE
Documenting weirdness with Social app update

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/social#1093]
So this afternoon I updated a bunch of apps from the Nextcloud WebUI. After it attempted to update social, Nextcloud stopped working entirely and said Upgrade required. I have no idea what happened here, but I fixed it with 
```
sudo bash /var/scripts/update.sh
nextcloud_occ app:disable social
sudo reboot
```

**Comment by kowalski7cc** [comment]
It seems the same issue DasSkelett (and I) found: https://github.com/nextcloud/social/issues/1034#issuecomment-712907192

**Comment by jancborchardt** [comment]
Thanks for the catch @kowalski7cc – closing this as duplicate of #1034 then. :)
