### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#110]
It should be possible to search for anything:
- words in posts
- users
- hashtags #108

**Comment by daita** [comment]
I would gladly implement this as an extension to the fulltextsearch

**Comment by jancborchardt** [comment]
We shouldn’t require an additional app though to be able to search through posts, no? Contacts or Calendar for example also doesn’t require fulltextsearch and searches inside of entries.

Or am I not updated and we ship fulltextsearch? :)

**Comment by daita** [comment]
I have no idea how a filled database will react if we start searching words in posts, we could try to do something light enough. Of course, we should do both for better UX.

**Comment by daita** [comment]
I implemented some multiple field search in #295 (account+hashtag). Once this is merge, I will add the search on Post into the results

**Comment by StCyr** [comment]
This has been implement @daita, doesn't it?

**Comment by daita** [comment]
I think we can close this one, yes. The search have been here for a while now !
