### ISSUE TITLE
nextcloud.occ social:reset produces error

### ISSUE THREAD

**Issue by seahost** [nextcloud/social#1129]
**Describe the bug**
When running **nextcloud.occ social:reset** the result is the following error.

An exception occurred while executing 'DELETE FROM `oc_social_3_client_auth`':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_social_3_client_auth' doesn't exist

**To Reproduce**
1. Have social installed
2. Run the nextcloud.occ social:reset command
3. Error

**Expected behavior**
It should reset/remove the social tables from the database.

<details>
<summary>Server details</summary>

**Social app version:**
0.4.1

**Operating system**:
Ubuntu Server 20.04.1

**Nextcloud version:** (see Nextcloud admin page)
Snap 20.01
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
o@nextcloud:~$ sudo snap run nextcloud.occ social:reset
[sudo] password for o: 
Beware, this operation will delete all content from the Social App.

Do you confirm this operation? (y/N) y
Operation is destructive. Are you sure about this? (y/N) y

flushing data... An exception occurred while executing 'DELETE FROM `oc_social_3_client_auth`':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_social_3_client_auth' doesn't exist

</details>

**Comment by dewomser** [comment]
Same exception here

**Comment by zeitgeist87** [comment]
I can reproduce this as well.

**Comment by tim-kilian** [comment]
Same error.

**Comment by xundeenergie** [comment]
I added this two tables manually
CREATE TABLE oc_social_3_client_auth (title VARCHAR(100) NOT NULL);
CREATE TABLE oc_social_3_client_token (title VARCHAR(100) NOT NULL);
and run occ social:reset again.

Then i was asked about my base-url.

But then i got another error...
`occ social:reset
Beware, this operation will delete all content from the Social App.

Do you confirm this operation? (y/N) y
Operation is destructive. Are you sure about this? (y/N) y

flushing data... done

Now is a good time to change the base address of your cloud:  (http://nextcloud.example.com) 
An unhandled exception has been thrown:
TypeError: Return value of "OCA\Social\Command\Reset::execute()" must be of the type int, "null" returned. in /var/www/html/custom_apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Social\Command\Reset), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/custom_apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/console.php(100): OC\Console\Application->run()
#6 /var/www/html/occ(11): require_once('/var/www/html/c...')
`

**Comment by ozls** [comment]
I managed to get around this bug by creating manually the two missing columns:
create table oc_social_3_client_auth (nocolumn int);
create table oc_social_3_client_token (nocolumn int);

**Comment by JOduMonT** [comment]
same here with nextcloud 20 and postgres

**Comment by seth586** [comment]
+1 same here can reproduce, nextcloud 20 & mariadb

**Comment by stefan123t** [comment]
I checked code in lib/Db/CoreRequestBuilder.php and it does not verify whether the tables actually have been created before emptying them. Suggesting to enclose it in function emptyAll() like in the other uninstallSocialTables() method.

                        if ($schema->hasTable($table)) {
                             $qb->delete($table);
                        }

**Comment by sledz** [comment]
> Now is a good time to change the base address of your cloud: (http://nextcloud.example.com)
An unhandled exception has been thrown:
TypeError: Return value of "OCA\Social\Command\Reset::execute()" must be of the type int, "null" returned. in /var/www/html/custom_apps/mail/vendor/symfony/console/Command/Command.php:261

I see the same behavior here. Is there a fix or workaround for this in the meantime?

**Comment by stefan123t** [comment]
@sledz workaround has been documented above and works around successfully. same for the fix it has been suggested but afaik not yet implemented / submitted as a pull request. Shame on me, I do not know how to handle that yet on my command line git.

**Comment by sledz** [comment]
@stefan123t I am unsure exactly what the "documented workaround" is supposed to be?

**Comment by stefan123t** [comment]
Both @xundeenergie and @ozls did create the two missing tables in order to call occ social:reset

The proposed fix should verify and delete only existing tables. Hence if they are missing, they need not be deleted or purged from the Database repository whatever the DB backend is (MariaDB, MySQL, PostGreSQL, you name it).

Kind regards,
Stefan

**Comment by stefan123t** [comment]
I have submitted the above PR #1330 to fix the issue at hand, i.e. trying to empty tables which do not exist.
Unfortunately the @continuous-integration/drone/pr is failing to get the CA certificate for the dependency on friendi.ca
Maybe someone of the friendly developers at nextcloud/social (eg. @juliushaertl) knows how to restart the CI engine and merge the code ?

**Comment by sledz** [comment]
@stefan123t I tried to apply your patch https://github.com/stefan123t/social/commit/17666a5f74c93d63212a8eb78a13c6ff8358be28 manually. But after that the assertion only changed to:

`flushing data... An unhandled exception has been thrown:
Error: Call to a member function hasTable() on null in /srv/www/htdocs/nextcloud/apps/social/lib/Db/CoreRequestBuilder.php:1204
`

So this does not really seems to be the solution. 🤔
