### ISSUE TITLE
Can't activate Social on NC 20.0.4

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/social#1164]
When i'm try to activate Social on NC 20.0.4 i got this error:

An exception occurred while executing 'DROP INDEX oc_social_3_cache_actor_pkey': SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR: cannot drop index oc_social_3_cache_actor_pkey because constraint oc_social_3_cache_actor_pkey on table oc_social_3_cache_actor requires it HINT: You can drop constraint oc_social_3_cache_actor_pkey on table oc_social_3_cache_actor instead.

System is running with:
php 7.4
postgresSQL

**Comment by Tachi107** [comment]
Search for existing issues before opening new ones.
This is the same issue as [#1034](https://github.com/nextcloud/social/issues/1034#issuecomment-716607398)

**Comment by violoncelloCH** [comment]
closing as duplicate of #1034
