### ISSUE TITLE
Can neither follow nor be followed

### ISSUE THREAD

**Issue by ozls** [nextcloud/social#1187]
**Describe the bug**
No matter what I do, I cannot manage to follow or be followed and my timeline stays empty. I am running Nextcloud on a RPI 4 with 4GB RAM with no issue. I don't have any warning in the administration overview. I think I correctly set up my .well-known/webfinger redirect, but I get a "missing ressource" and no JSON when I try to access https://domain.xyz/.well-known/webfinger?resource=acct:user@domain.xyz... I have tried `occ social:reset` many times, I have uninstalled and reinstalled, cleared the database myself, nothing works. I know it is not the purpose of the issues to help beginners, but I would really like to make it work and at this point I don't know what else to do.

Here are my .htaccess and virtual host files:
- .htaccess: https://pastebin.com/8tgiAD62
- nextcloud.conf: https://pastebin.com/MAWBcN0L

<details> 
<summary>Server details</summary>

**Social app version:**
0.4.2
**Operating system**:
Raspbian 10 (buster) arm64
**Web server:**
Apache 2
**Database:**
mysql 10.3.27 
**PHP version:**
7.4.13
**Nextcloud version:**
20.0.5
</details>

**Comment by stefan123t** [comment]
@ozls, take a look at my .htaccess config under #808 i had to include the https://%{SERVER_NAME}/ in all my RewriteRules to make the well_known/webfinger issues go away some days ago in order to upgrade from nextcloud 20.0 to 20.5.
I have noticed that you still have the /dav/ in your caldav and carddav URLs too, which caused problems earlier and was fixed in documentation by removing the trailing slash, ie. /dav is sufficient.

Maybe you also need to update social_address and cloud_address to make your webfinger return some values.
```
wget https://example.net/.well-known/webfinger?resource=acct:user@example.net
{"subject":"acct:user@example.net","links":[{"rel":"self","type":"application\/activity+json","href":"https:\/\/example.net\/nextcloud\/nextcloud\/index.php\/apps\/social\/@user"},{"rel":"http:\/\/ostatus.org\/schema\/1.0\/subscribe","template":"https:\/\/example.net\/nextcloud\/index.php\/apps\/social\/ostatus\/follow\/?uri={uri}"}]}
```

**Comment by ozls** [comment]
Thanks for looking into this @stefan123t ! Unfortunately, I have done everything you mentioned and it still doesn't work. The only difference I can think of is my removing the `/nextcloud/index.php` part of my URLs.

**Comment by ozls** [comment]
Ok I solved it. I just found out I had kept the following redirects in my virtual host file:
```
    Redirect 301 /.well-known/carddav /remote.php/dav
    Redirect 301 /.well-known/caldav /remote.php/dav
    Redirect 301 /.well-known/webfinger /public.php?service=webfinger
```
Once I removed them (it was already handled by my .htaccess) everything worked as expected. Thanks @stefan123t !

**Comment by stefan123t** [comment]
Glad to hear that has been solved. Just had the same difficulties seeing the problem with too many or wrong redirect/rewrite rules. The test using curl against the webfinger helped me track my problem down. Cheers Stefan
