### ISSUE TITLE
Cannot parse Create [...] Unknown parameter type, 64 given

### ISSUE THREAD

**Issue by Tyil** [nextcloud/social#1208]
**Describe the bug**

The social app is currently not correctly handling incoming data from other instances, failing with the following error message: `Cannot parse Create: Doctrine\\DBAL\\Exception\\DriverException An exception occurred while executing a query: Unknown parameter type, 64 given.`.

**To Reproduce**

1. `cd $nextcloud_dir/apps`
2. `git clone https://github.com/nextcloud/social.git`
3. `cd social`
4. `git checkout v0.4.2`
5. `make dev-setup`
6. `make build-js`
7. `cd ..`
8. `php occ app:enable social`
9. Follow some people, and wait for incoming requests.

**Expected behavior**

Incoming events should be handled properly, or at least provide information to fix the issue.

<details>
<summary>Server details</summary>

**Social app version:** 0.4.2

**Operating system**: Gentoo GNU+Linux

**Web server:** nginx

**Database:** postgresql

**PHP version:** 7.4

**Nextcloud version:** 21.0.0
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{
  "reqId": "AS24Vg22OlzPeEf6chwF",
  "level": 2,
  "time": "2021-02-24T05:56:40+00:00",
  "remoteAddr": "67.205.187.155",
  "user": "--",
  "app": "social",
  "method": "POST",
  "url": "/apps/social/inbox",
  "message": "Cannot parse Create: Doctrine\\DBAL\\Exception\\DriverException An exception occurred while executing a query: Unknown parameter type, 64 given.",
  "userAgent": "http.rb/4.4.1 (Mastodon/3.3.0; +https://mastodon.technology/)",
  "version": "21.0.0.18"
}
{
  "reqId": "XMMZaElybgCMuf4y1zOl",
  "level": 2,
  "time": "2021-02-24T06:09:54+00:00",
  "remoteAddr": "51.91.68.228",
  "user": "--",
  "app": "social",
  "method": "POST",
  "url": "/apps/social/inbox",
  "message": "Cannot parse Create: Doctrine\\DBAL\\Exception\\DriverException An exception occurred while executing a query: Unknown parameter type, 64 given.",
  "userAgent": "http.rb/4.4.1 (Mastodon/3.3.0; +https://fosstodon.org/)",
  "version": "21.0.0.18"
}
```

</details>

**Comment by daita** [comment]
fixed in 0.5.0
