### ISSUE TITLE
Emoji picker icon not inverted in dark theme

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#132]
![emoji picker not visible with dark theme](https://user-images.githubusercontent.com/925062/49479432-49c52200-f823-11e8-9ca0-a4187da7baca.png)

But everything else works :+1: !

**Comment by juliushaertl** [comment]
@violoncelloch Maybe this is a nice one for you :wink: 

We basically need a icons.scss file which uses the mixin (`icon-black-white()`) we provide in the server to generate a black and white version of the icon:

https://docs.nextcloud.com/server/latest/developer_manual/design/css.html#icons

**Comment by violoncelloch** [comment]
oh, thank you @juliushaertl !
I'll look into it when I've got some time. Is there an (estimated) due date for v0.2?

**Comment by violoncelloCH** [comment]
@juliushaertl
I'm finally trying to do this, but I think I would need the source .svg file of the base64 data uri string
```
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2OCIgaGVpZ2h0PSI2OCI+PHBhdGggZD0iTTM0IDBDMTUuMyAwIDAgMTUuMyAwIDM0czE1LjMgMzQgMzQgMzQgMzQtMTUuMyAzNC0zNFM1Mi43IDAgMzQgMHptMCA2NEMxNy41IDY0IDQgNTAuNSA0IDM0UzE3LjUgNCAzNCA0czMwIDEzLjUgMzAgMzAtMTMuNSAzMC0zMCAzMHoiLz48cGF0aCBkPSJNNDQuNiA0NC42Yy01LjggNS44LTE1LjQgNS44LTIxLjIgMC0uOC0uOC0yLS44LTIuOCAwLS44LjgtLjggMiAwIDIuOEMyNC4zIDUxLjEgMjkuMSA1MyAzNCA1M3M5LjctMS45IDEzLjQtNS42Yy44LS44LjgtMiAwLTIuOC0uOC0uOC0yLS44LTIuOCAweiIvPjxjaXJjbGUgcj0iNSIgY3k9IjI2IiBjeD0iMjQiLz48Y2lyY2xlIHI9IjUiIGN5PSIyNiIgY3g9IjQ0Ii8+PC9zdmc+);
```
or is there an other way to do this without a .svg?

**Comment by violoncelloCH** [comment]
nevermind, found a way to decode the base64...
