### ISSUE TITLE
Search on incomplete account

### ISSUE THREAD

**Issue by daita** [nextcloud/social#140]
There is 2 searchs on the front-end.

The first one is done when typing an account (starting with '@') in the post creation text field. This search is only looking within the cache of the accounts (local & remote)

The second one, using the default search box is searching on remote instance (in case there is no cached version). This one is an issue as it permanently search while typing meaning that some request are sent to unknown host. We need to only trigger the search on an event like 'Enter'

**Comment by daita** [comment]
should be done in alpha 2.0

**Comment by StCyr** [comment]
cannot reproduce here @daita 

Could you please provide a more detailed scenario?
