### ISSUE TITLE
master 

### ISSUE THREAD

**Issue by octavsly** [nextcloud/social#1457]
**Describe the bug**
make dev-setup 
**on master branch fails with dependency conflict**

**To Reproduce**
1. Run make dev-setup 

**Expected behavior**
to properly finish the dependency 

**Log**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @babel/eslint-parser@7.17.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.8.0" from the root project
npm ERR!   peer eslint@">=5.0.0" from @nextcloud/eslint-plugin@1.5.0
npm ERR!   node_modules/@nextcloud/eslint-plugin
npm ERR!     dev @nextcloud/eslint-plugin@"^1.5.0" from the root project
npm ERR!   10 more (@typescript-eslint/parser, babel-eslint, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.5.0 || ^8.0.0" from @babel/eslint-parser@7.17.0
npm ERR! node_modules/@babel/eslint-parser
npm ERR!   peer @babel/eslint-parser@"^7.16.5" from @nextcloud/eslint-config@8.0.0
npm ERR!   node_modules/@nextcloud/eslint-config
npm ERR!     dev @nextcloud/eslint-config@"^8.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.21.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.5.0 || ^8.0.0" from @babel/eslint-parser@7.17.0
npm ERR!   node_modules/@babel/eslint-parser
npm ERR!     peer @babel/eslint-parser@"^7.16.5" from @nextcloud/eslint-config@8.0.0
npm ERR!     node_modules/@nextcloud/eslint-config
npm ERR!       dev @nextcloud/eslint-config@"^8.0.0" from the root project

**Social app version:**
master branch 

**Operating system**:
Linux gentoo

**Web server:**
apache

**Database:**
mysql

**PHP version:**
8

**Nextcloud version:** (see Nextcloud admin page)
24.0.3

**Comment by CarlSchwan** [comment]
Fixed on the new master
