### ISSUE TITLE
[0.1.x] Known issues.

### ISSUE THREAD

**Issue by daita** [nextcloud/social#153]
- [ ] Creating a post as 'Unlisted' is not working as expected.
- [ ] message saying that '.well-known is wrongly configured' is displayed on the first launch of the app. A simple refresh fix this.  @juliushaertl 
- [ ] missing Notification Stream (so if anyone is taggin you on a public message, you wont see the message ...)
- [ ] You don't see your own posts in the Home Stream if you're following no one.  → https://github.com/nextcloud/social/issues/166

**Comment by jancborchardt** [comment]
@daita (cc @juliushaertl) same here, please open individual issues and use the Milestone to manage. :)
