### ISSUE TITLE
Delete your own post

### ISSUE THREAD

**Issue by daita** [nextcloud/social#155]
We need to add a way to delete  your own post on the UI, and manage this on the back-end

**Comment by jancborchardt** [comment]
Interface-wise, there should be a 3-dot icon on the right next of the posting date of a post. This would open a menu with the usual:
- Pin on profile #125 
- Delete
- Delete & re-draft (Mastodon has this, restoring the post in the compose controls so you can basically "edit" it.)

Documentation about the popover menu at https://docs.nextcloud.com/server/15/developer_manual/design/popovermenu.html

**Comment by MariusBluem** [comment]
<img width="577" alt="bildschirmfoto 2018-12-11 um 16 11 48" src="https://user-images.githubusercontent.com/19711361/49809578-91860500-fd5f-11e8-9020-6cad9158ee2c.png">

I'd say deleting posts would make sense :) Thanks for demonstrating this @mathiasconradt @schiessle
