### ISSUE TITLE
[UI] Ability to reply to a Post.

### ISSUE THREAD

**Issue by daita** [nextcloud/social#158]
Theoretically, the back-end is already able to do that, an implementation on the UI should be enough. The idea is to fill the 'replyTo' field with the Id of the original post during the creation of the Post

**Comment by jancborchardt** [comment]
Cool! For replying, we can use this icon from the Mail app:
![](https://raw.githubusercontent.com/nextcloud/mail/master/img/reply.png)
https://github.com/nextcloud/mail/blob/master/img/reply.svg
