### ISSUE TITLE
Following nextcloud@mastodon.xyz on first login works but displays an error

### ISSUE THREAD

**Issue by daita** [nextcloud/social#161]
On first use of the app, I got an error in console (and also a notification) but in the end I am following the account after clicking the link.

There is also an issue when displaying the emoji from the Nextcloud account:
![selection_051](https://user-images.githubusercontent.com/1038617/49641924-21931a00-fa01-11e8-8a8b-e0c1eb990631.png)

**Comment by juliushaertl** [comment]
> On first use of the app, I got an error in console (and also a notification) but in the end I am following the account after clicking the link. 

What kind of an error?

> There is also an issue when displaying the emoji from the Nextcloud account:

Ah yes, we need to apply twemoji to that as well.

**Comment by daita** [comment]
could be related to #175

**Comment by schiessle** [comment]
I'm not sure if it is just an error message. Also after trying to follow the Nextcloud account my "follow" count is still zero:

![image](https://user-images.githubusercontent.com/1589737/49695943-96518a00-fba2-11e8-97cd-3c688daaaa10.png)

and if you look here https://mastodon.xyz/users/nextcloud/followers you can't find me in the followers list. Also there is no notification on the Nextcloud account at mastodon.xyz that I started follow them. So I'm pretty sure that it fails completely, at least in some circumstances

**Comment by daita** [comment]
#194 should do the trick

**Comment by daita** [comment]
should be fixed in 0.1.1
