### ISSUE TITLE
Follow button shown for own account

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/social#1627]
**Describe the bug**
When I go to someones following list and the user follows me, then a "Follow" button appears next to my account (error is thrown when trying to follow)

**To Reproduce**
1. User 2 follows User 1
2. User 1 goes to User 2's profile to the following list
3. User 1 appears in the following list including a "Follow" button

**Expected behavior**
The "Follow" button shouldn't be shown for the own account.

**Client details:**
 - OS: Web
 - Browser: Firefox
 - Version: 110
 - Device: Desktop

**Comment by artonge** [comment]
Should be fixed by https://github.com/nextcloud/social/pull/1615
