### ISSUE TITLE
Avatar not displayed after updating the privacy settings

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/social#163]
Steps to reproduce:
1. Have the avatar privacy settings set to contacts
2. Create a social account
3. Change the avatar privacy settings to public

Expected behavior: 
The avatar url is added to the activitypub response

Actual behavior: 
The avatar url is still missing

**Comment by daita** [comment]
This is done during the next refresh of the cache (cron)

We could catch the event for this edit and refresh the cache at this point.

**Comment by juliushaertl** [comment]
I did run the cron and occ social:cache:refresh. I guess the cache is only updated if the avatar version changes, which is not the case if the privacy setting is updated.

**Comment by daita** [comment]
What is your account ?

**Comment by juliushaertl** [comment]
Was on my personal instance.

**Comment by juliushaertl** [comment]
I could not reproduce this with latest master anymore.
