### ISSUE TITLE
Own posts should also appear under "Home"

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/social#166]
On cloud.nextcloud.com: own posts should also appear under "Home". Currently they don't.

**Comment by violoncelloch** [comment]
this is already covered by #153 but as @jancborchardt suggested to split #153 up we maybe keep this one open and remove the point from #153?

**Comment by daita** [comment]
@mathiasconradt just to confirm, do you still have issue right now ? if so, can you follow an account and check your Home stream ?

**Comment by mathiasconradt** [comment]
@daita Tried to follow you via https://cloud.nextcloud.com/apps/social/account/@maxence/ , does not owrk.

**Comment by mathiasconradt** [comment]
@daita Issue is resolved now (Home).

Following does not work, see https://github.com/nextcloud/social/issues/165
