### ISSUE TITLE
Unable to open Profile

### ISSUE THREAD

**Issue by srijansaxena11** [nextcloud/social#1701]
**Describe the bug**
When trying to open profile it gets stuck at loading the page.

**To Reproduce**
1. Go to social app
2. Click on Profile

**Expected behavior**
Profile should open.

But it doesn't and the page keeps on loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/34964694/227533903-21524988-4b1f-44ff-9502-b7b86fc7ba88.png)

**Client details:**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version 11
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:** 0.6.0-beta5

**Operating system**: Ubuntu 22.04.1 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1.2

**Nextcloud version:** (see Nextcloud admin page) 26.0.0
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

vue.runtime.esm.js:3049 
        
       TypeError: Cannot read properties of undefined (reading 'id')
    at Profile.vue:100:1
    at p (Profile.vue:44:1)
    at Generator.<anonymous> (Profile.vue:44:1)
    at Generator.next (Profile.vue:44:1)
    at p (Profile.vue:44:1)
    at a (Profile.vue:44:1)
```

</details>

**Comment by roelfrenkema** [comment]
Same here also webfinger seems not to work. Related?

**Comment by srijansaxena11** [comment]
> Same here also webfinger seems not to work. Related?

Webfinger works fine. The profile still doesn't work though.

**Comment by srijansaxena11** [comment]
Do we have any update on this? Anything to try out? Any updates or anything under development to fix it?

**Comment by ArtificialOwl** [comment]
can you replicate the issue after installing https://github.com/nextcloud-releases/social/releases/download/v0.6.0-rc1/social-v0.6.0-rc1.tar.gz ?

**Comment by srijansaxena11** [comment]
> can you replicate the issue after installing https://github.com/nextcloud-releases/social/releases/download/v0.6.0-rc1/social-v0.6.0-rc1.tar.gz ?

Hi @ArtificialOwl . I am on rc1 only: 
![image](https://user-images.githubusercontent.com/34964694/231756920-6f93ab09-212c-4b3e-9607-aeb1f536e7e5.png)

This is what is on line 100 of Profile.vue:
![image](https://user-images.githubusercontent.com/34964694/231757243-ce3cbf34-44bd-4dcc-a058-5e2ca3dca112.png)

Should it be this.id instead of this.accountInfo.id as in the response of the request that is called on clicking profile (https://nextcloud.domain/apps/social/api/v1/global/account/info?account=user@nextcloud.domain), I cannot find accountInfo in JSON but I can see id.

**Comment by srijansaxena11** [comment]
I have set it up on my local and replicated the issue. this.profileAccount is giving value but this.accountInfo is undefined. I tried to put loggers at multiple places to find out the issue but couldn't. If anyone can guide me, I would be happy to assist in resolving this.

**Comment by srijansaxena11** [comment]
So for local account what is happening is the state.accountIdMap has reference too username@localhost but the account that is passed to it to retrieve the accountInfo is username@nextcloud.domain
