### ISSUE TITLE
Name display inconsistent

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#171]
Above the posting box, it shows your display name and your full handle with domain – this is how it should be.

In the stream and on your profile page though it shows just the Nextcloud username of you and others. This is not useful, except when there’s no display name set for the person.

![social app names](https://user-images.githubusercontent.com/925062/49678284-a0c93200-fa83-11e8-96e8-060c571d627f.png)

![social name](https://user-images.githubusercontent.com/925062/49678283-a0309b80-fa83-11e8-9acb-2b14340f9108.png)

@violoncelloch maybe this is also a good simple templating thing, if you want to look into that? :)

**Comment by violoncelloch** [comment]
`actore_info.preferredUsername` is used there which returns the username and not the display name.
@juliushaertl does there exist a variable containing the displayName for the actor or do we have to create one first in the backend? Above the posting box `currentUser.displayName` is used.

**Comment by jancborchardt** [comment]
@juliushaertl @daita do you have a pointer for @violoncelloCH? :)

**Comment by juliushaertl** [comment]
@violoncelloCH displayName is the one that should be used. It should be available on all person object that are returned. prefferedUsername is the first part of the full cloud id. Note that the displayName might be empty, so in places where the full social id (prefferedUsername@cloud.example.com) isn't shown, we should display at least the prefferedUsername.

**Comment by jancborchardt** [comment]
@juliushaertl preffered → preferred :wink: 

@violoncelloCH Also now with #244 (Public page frontend fixes) the username shows in the page title, which should also be the displayName.

**Comment by violoncelloCH** [comment]
@juliushaertl `item.actor_info.displayName` is always empty, that's why I'm struggling atm. I also can't find a place where something else than `item.actor_info.preferredUsername` is used (expect the `currentUser.displayName` above the Composer)

**Comment by juliushaertl** [comment]
@violoncelloCH Sorry, I missed the notification on this one. I didn't remember the propert name correct. It is actor_info.name for the display name.

**Comment by violoncelloCH** [comment]
thank you for your reply @juliushaertl 
Your commit c3918c3ae8e4cbcc41a637bcccdc3305c41e7b8d should have already addressed this, shouldn't it? At least with the new method `userDisplayName()` `actor_info.name` should be used if available, but this still doesn't work for me. Looks like `actor_info.name` is empty as well for local users with a Display Name set in user settings.

**Comment by juliushaertl** [comment]
ah right, thanks for noticing @violoncelloCH This is already fixed.
