### ISSUE TITLE
Issues with public profile page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#172]
- [x] The "public" page of a user only shows when you are logged in. Which defeats the purpose of course. 
    ![social public page logged in](https://user-images.githubusercontent.com/925062/49678412-51cfcc80-fa84-11e8-8f69-f6e077df2379.png)
    In private mode or when not logged in, it’s empty with some errors:
    ![social public page private mode](https://user-images.githubusercontent.com/925062/49678411-51cfcc80-fa84-11e8-86c9-598335dc6ad6.png)
- [x] In the header it says "Social `username`". It should just say "Social" as the profile is directly below.
- [x] In the title it only says "Nextcloud". It should say "`Name` - Social - Nextcloud" as we do in other apps too. The most specific thing on the left.
- [x] The tab "Posts" should shown and selected by default.

**Comment by schiessle** [comment]
btw, wouldn't it be nice to use `https://<your-nextcloud>/@user` as profile page, without the `apps/social` part, at least as a redirect? This would make it easier to discover and remember user profiles and most people know this pattern already from Mastodon.

**Comment by jancborchardt** [comment]
@schiessle great point – could you open a separate issue for it? :)

**Comment by mknet** [comment]
@jancborchardt Is there anything I have to configure to activate public profiles? I always get the login form, though I'm using https://domain/index.php/apps/social/@user/

Thanks for your help

**Comment by daita** [comment]
please create a new issue for this one !

**Comment by mknet** [comment]
Okay, will do so.

**Comment by octavsly** [comment]
> Okay, will do so.

what is the new issue number?
