### ISSUE TITLE
"File not found" when clicking link of full ActivityPub handle

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#173]
When I go to https://cloud.nextcloud.com/apps/social/@maxence it works.

But when I go to https://cloud.nextcloud.com/apps/social/@maxence@cloud.nextcloud.com or https://cloud.nextcloud.com/apps/social/@nextcloud@mastodon.xyz I get this:
![social file not found](https://user-images.githubusercontent.com/925062/49678671-3b2a7500-fa86-11e8-9fc1-acf4249f8a10.png)

**Comment by juliushaertl** [comment]
Fixed by #264
