### ISSUE TITLE
Why no release for Nextcloud 26?

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/social#1769]
I have seen that version 0.6.0 is officially released, but I have seen there is only a release for Nextcloud 27. Why not for Nextcloud 26? Is there a reason for this?

**Comment by daffydock** [comment]
Albeit it might be only a guess, perhaps it is being done as to re-launch the app along with the incoming 27 version, as a add a marketing, promotional push. Since 26 is already out. I have two instances, one is already on 27 so I will definitely will be playing with it, so see how it works.

**Comment by Moonbase59** [comment]
Sadly, Social doesn’t seem to get much love. Almost no updates and urgently needed bug fixes since the initial hype two or three years ago.

**Comment by ArtificialOwl** [comment]
0.6.1 will be available on nc26
