### ISSUE TITLE
Needs a new release published: v0.6.1 is missing recent merged PRs

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/social#1887]
v0.6.1 was published 11 months ago and lacks important already merged PRs such as #1865.

This is breaking installations even though these bugs were already fixed :)

**Comment by Mannshoch** [comment]
Ping @juliushaertl  @ArtificialOwl 
Or is this project death?

**Comment by joshtrichards** [comment]
Fixed in 20d668ea60a9730dbd566da12785940056bcb30b

Also see #1889
