### ISSUE TITLE
SQL Error: Row size too large when enabling Social app.

### ISSUE THREAD

**Issue by zerojay** [nextcloud/social#207]
**Describe the bug**
Attempting to enable the Social app results in a failure with the following output:

An exception occurred while executing 'ALTER TABLE oc_social_cache_actors CHANGE `source` source VARCHAR(10000) NOT NULL COLLATE utf8mb4_bin': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**To Reproduce**
Update Social to latest version from git.

**Expected behavior**
Social app gets enabled and begins being functional.

**Social app version:** 0.1 git

**Operating system**: Ubuntu 18.04.1

**Web server:** Apache 2.4.x

**Database:** MySQL 5.7.24

**PHP version:** 7.2 FPM

**Nextcloud version:** 15.0

**Comment by jancborchardt** [comment]
@daita is this fixed by one of your pull requests? :)

**Comment by zerojay** [comment]
Updated the OS version (sorry, got slightly confused) and added the MySQL version. What configuration information do you need to know about MySQL? I don't remember making many changes to the initial configuration as Ubuntu ships.

`
mysql> SHOW COLUMNS FROM oc_social_server_notes;
+----------------+---------------+------+-----+---------+-------+
| Field          | Type          | Null | Key | Default | Extra |
+----------------+---------------+------+-----+---------+-------+
| id             | varchar(127)  | NO   | PRI | NULL    |       |
| type           | varchar(31)   | NO   |     | NULL    |       |
| to             | varchar(127)  | NO   |     | NULL    |       |
| to_array       | varchar(2000) | NO   |     | NULL    |       |
| cc             | varchar(127)  | NO   |     | NULL    |       |
| bcc            | varchar(127)  | NO   |     | NULL    |       |
| content        | varchar(3000) | NO   |     | NULL    |       |
| summary        | varchar(3000) | NO   |     | NULL    |       |
| published      | varchar(31)   | NO   |     | NULL    |       |
| published_time | datetime      | YES  |     | NULL    |       |
| attributed_to  | varchar(127)  | YES  |     | NULL    |       |
| in_reply_to    | varchar(127)  | YES  |     | NULL    |       |
| source         | varchar(3000) | NO   |     | NULL    |       |
| instances      | varchar(3000) | NO   |     | NULL    |       |
| creation       | datetime      | YES  |     | NULL    |       |
| local          | tinyint(1)    | NO   |     | 0       |       |
+----------------+---------------+------+-----+---------+-------+
16 rows in set (0.00 sec)
`

**Comment by daita** [comment]
Could you test this patch ?

Please check that you only have 2 Migrations file in the social/lib/Migration/ : https://github.com/nextcloud/social/tree/c1e387c08fe63881d293266422ad2bcf0033566e/lib/Migration

Doing an hacky: `./occ config:app:set --value '0.0.1' social installed_version` and refresh the webclient of Nextcloud will trigger the updating process.

**Comment by zerojay** [comment]
Yes, I only had two files in there originally. The patch appears to have worked for me. I no longer see errors in my logs.
