### ISSUE TITLE
Following @nextcloud@mastodon.xyz fails

### ISSUE THREAD

**Issue by hillebr** [nextcloud/social#208]
When trying to follow @nextcloud@mastodon.xyz with my recently upgraded NextCloud instance 
portal.christinahillebrand.de I got the error:
"The required redirect URL for your account could not be found"
Social App was installed via AppStore.
.htaccess settings .well-known etc. applied!
Do I have to set up / adjust anything else?

TIA

René

**Comment by violoncelloch** [comment]
duplicate of #161
