### ISSUE TITLE
Check with ActivityPub test suite

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#209]
The page https://activitypub.rocks has a test suite at https://test.activitypub.rocks

We should check Social with that and make sure it passes. :) @nextcloud/social

**Comment by daita** [comment]
Hello @annando ! nice to see you on github too :-p

**Comment by rhonda** [comment]
I'm uncertain if that test suite there is really worth looking at, given that the certificate expired two months ago?  Is this still in use?

**Comment by annando** [comment]
I guess that something like this is more promising: https://testsuite.feneas.org/

**Comment by daita** [comment]
duplicated with #1014
