### ISSUE TITLE
Facebook support

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/social#211]
Currently supported are Nextcloud, 🐘 Mastodon, 🇫 Friendica, and soon ✱ Diaspora and👹 MediaGoblin.

That is so awesome it's not funny! Social Media Platform interoperability is a dream of sorts. 

But Facebook support is what will empower and encourage a significant migration away form Facebook I suspect. Just a thought.

**Comment by genofire** [comment]
Facebook has no interoperability interface to other networks, so this would not be possible.

Maybe you could convince Facebook to implement [ActivityPub](https://www.w3.org/TR/activitypub/) a protocol behind that. (Sorry, i bad joke i know)

**Comment by bernd-wechner** [comment]
Well noted. ActivityPub looks awesome. Looks like its Collections generalize the idea of groups, pages and such on FB quite well, and while you think it a bad joke, and I agree I don't see FB adopting it in any hurry of their own accord, FB and other giants are facing increasing scrutiny from legislators because of growing monopolies, that like the telecoms before them emerge because of intentional lack of interoperability - by which I mean, the day may come when FB is legislated to support something like ActivityPub, and interoperability (much as telecoms were when their monopolies were broken up).

**Comment by daita** [comment]
like @genofire said, the social app is based on ActivityPub and will only manage ActivityPub

**Comment by jjisnow** [comment]
Facebook does allow you to "Download your information" under Settings -> Your Facebook information -> Download your information. It can be done in HTML or JSON. Does anyone know a good JSON/HTML to ActivityPub parser?
