### ISSUE TITLE
app user_webfinger missing

### ISSUE THREAD

**Issue by hillebr** [nextcloud/social#218]
The app user_webfinger seems to be a prerequisite to the social app.
This app is missing on my instance.
I can't find it within AppStore so how do I install it?

TIA

René

**Comment by daita** [comment]
No, there is no prerequisite beside Nextcloud 15.
Why would you think the app user_webfinger would be needed ?

**Comment by hillebr** [comment]
because Social app advised me after installation to add some RewriteRules to upper my .htaccess
RewriteRule ^\.well-known/host-meta /nextcloud/public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /nextcloud/public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/webfinger /nextcloud/public.php?service=webfinger [QSA,L]
If I call \.well-known/host-meta for instance I got the error:

Exception: App not installed: user_webfinger

**Comment by hillebr** [comment]
...and original NextCloud .htaccess does contain:
 RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /public.php?service=webfinger [QSA,L]

**Comment by daita** [comment]
did you already open the social App in your browser ?

**Comment by hillebr** [comment]
...yes!The app works, but I can't follow nextcloud@mastodon.xyz even after adding the two lines of #161See my #208HTHRené-------- Originalnachricht --------Betreff: Re: [nextcloud/social] app user_webfinger missing (#218)Von: Maxence Lange An: nextcloud/social Cc: hillebr ,Author did you already open the social App in your browser ?

**Comment by daita** [comment]
This will be fixed in 0.1.1
