### ISSUE TITLE
[Discussion] Post to groups

### ISSUE THREAD

**Issue by christoph-puppe** [nextcloud/social#231]
Hi

I'd love to be able to post to local groups.

Please :)

**Comment by juliushaertl** [comment]
cc @daita Is there some specification in activity pub to have groups to post to?

**Comment by daita** [comment]
looks like there is a Group object in ActivityPub, that you can Join, Invite, ...

**Comment by juliushaertl** [comment]
_[poVoq](/poVoq) wrote in #427:_ 

> **Is your feature request related to a problem? Please describe.**
> Would be nice to allow people to write to a group on Nextcloud social and have automatically a group channel that can be written to by using the !bang tag like in Friendica, Hubzilla or GNUSocial.
> 
> **Describe the solution you'd like**
> Compatible group / forum channel implementation similar to Friendica or Hubzilla on ActivityPub that you can follow via `*groupname*@yournextclouddomain.xyz` and write to via `!*groupname*@nextclouddomain.xyz`
> Groups should be of course created from the Nextcloud internal groups and/or maybe circles.
> 
> Thanks for considering.

**Comment by daita** [comment]
duplicated/related to #1007

**Comment by jancborchardt** [comment]
Let’s close in favor of https://github.com/nextcloud/social/issues/1007
