### ISSUE TITLE
Nextcloud behind proxy shows IP instead of hostname

### ISSUE THREAD

**Issue by ronnicek** [nextcloud/social#234]
**Describe the bug**
Home (or profile) shows 192.168.0.100 instead of nextcloud.domain.com

**To Reproduce**
1. Run nginx in docker infront of php7-fpm in docker with nextcloud
2. Click on 'Social'
3. See error

**Expected behavior**
Social app should show nextcloud.domain.com instead of IP

**Screenshots**
![social-bug](https://user-images.githubusercontent.com/3885042/50057503-7f470500-016b-11e9-9af7-6b1ebb71b3eb.png)

**Client details:**
 - OS: Windows
 - Browser Firefox
 - Version 64
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:**
 0.1.0

**Operating system**:
Alpine Linux

**Web server:**
Nginx

**Database:**
SQLite

**PHP version:**
7.2.13

**Nextcloud version:** (see Nextcloud admin page)
15.0

</details>

**Comment by ronnicek** [comment]
This looks the same as #233 maybe? If yes, sorry and feel free to close it :)

**Comment by ronnicek** [comment]
Yep, I had 'overwrite.cli.url' => 'https://192.168.0.19' in configuration.. closing.

**Comment by violoncelloCH** [comment]
yes, exactly, thank you!
