### ISSUE TITLE
German Translation missing

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/social#237]
**Describe the bug**
Transifex says; German Translation for this app = 100%. With default_language = "de" and default_locale = "de" in config.php and Userconfig, the app still shows english text.

It looks like the translationsfiles are missing in l10n.

**Comment by juliushaertl** [comment]
@jancborchardt Can you add @nextcloud-bot as an admin to the repo? The transifex sync fails, since the bot doesn't have write access to the repo.

**Comment by daita** [comment]
done, but not sure if it might needs a confirmation to the invitation from the bot

**Comment by jancborchardt** [comment]
I can see the bot as admin of the repo, so it should work fine now?
