### ISSUE TITLE
Add "rsa-sha256" as "algorithm" to the HTTP signature

### ISSUE THREAD

**Issue by annando** [nextcloud/social#238]
Currently the HTTP signature is missing the "algorithm" field.

Please add ```algorithm="rsa-sha256"``` to the HTTP signature fields, like most other implementations are doing.

**Comment by jancborchardt** [comment]
@annando would you be interested in contributing this fix? :slightly_smiling_face:  The development setup instructions are at https://github.com/nextcloud/social#development-setup, let us know if you need any help!

**Comment by annando** [comment]
Currently I'm still running with version 14, since the update process hadn't offered me the update yet. And I'm running it on my NAS, I'm not sure if I can setup a development environment there.

**Comment by jancborchardt** [comment]
Fixed through https://github.com/nextcloud/social/pull/251
