### ISSUE TITLE
Send an "Accept" as answer to a "Follow"

### ISSUE THREAD

**Issue by annando** [nextcloud/social#239]
Currently contact requests from Friendica aren't shown as "accepted" on the Friendica side. This is related to the fact that Friendica awaits an "Accept Follow" message. This message is sent by most known implementations.

See here for details: https://w3c.github.io/activitypub/#follow-activity-inbox

**Comment by juliushaertl** [comment]
cc @daita Related to https://github.com/nextcloud/social/issues/36

**Comment by daita** [comment]
We do Accept on Follow request. I will have a look on why it's not working with Friendica

**Comment by daita** [comment]
This is the request I am sending back to you when I am receiving your request:

host: squeet.me
path: /inbox/cult
type: POST,
result: : 202

```
{
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1"
    ],
    "id": "/https:/test.artificial-owl.com/apps/social/@test1#accepts/follows/93dfde98-ff5a-4bc7-8019-a9e8bds01b25",
    "type": "Accept",
    "actor": "https://test.artificial-owl.com/apps/social/@test1",
    "object": {
      "id": "https://squeet.me/activity/9625c194757e06b1",
      "type": "Follow",
      "actor": "https://squeet.me/profile/cult",
      "object": "https://test.artificial-owl.com/apps/social/@test1"
    }
}
```

**Comment by annando** [comment]
Currently I cannot test it by myself, I'm still waiting for the updater telling me that there is a new version. On a first glance - and by looking into the logfile this looks okay.

Sorry for the false alarm.

**Comment by daita** [comment]
@annando, you can force an upgrade to 15 by 

- opening the Admin Settings/Overview page,
- selecting the update channel to 'beta',
- refresh the page,
- switch back to 'production'

You should see the NC15 update available

**Comment by annando** [comment]
This is my production system with valuable data on it - is it safe?

**Comment by jancborchardt** [comment]
We’re not in a rush here, maybe it’s just best to wait out until the update gets suggested to you. Sometimes takes a bit longer since we do this rollout in stages, and also you might want to wait for the first dot-release with fixes and such.

**Comment by annando** [comment]
Okay. If that's fine for you, then it's fine for me.

**Comment by Luzifer** [comment]
Using Nextcloud 15.0.0.10 and Social 0.1.1 this also occurs for a Mastodon 2.6.5 instance. The follow is listed in Social but the Mastodon instance states an approval is required. 

![image](https://user-images.githubusercontent.com/20142/50543330-b68acc80-0bd5-11e9-8888-4652c3e56858.png)

Also no updates from the Social account are shown on the Mastodon instance and the profile isn't loaded properly (lacking image, way too high follower count) but this might be another unreleated issue.

**Comment by daita** [comment]
@annando so I dived into friendica, and it seems that the normalization of the object is different/buggy.

Is https://git.friendi.ca/friendica/php-json-ld/src/branch/master/jsonld.php a fixed version of the original from `digitalbazaar` ?

(Source: 
https://github.com/friendica/friendica/blob/491fc5f78aadb787a57a0f0630779f457ff1bcb4/src/Util/LDSignature.php#L86-L89)

**Comment by daita** [comment]
ok, i will try with your package of ld-json, seems to work better.

**Comment by daita** [comment]
0.1.2 should have fixed this. Please confirm

**Comment by annando** [comment]
I cannot do tests by myself, since the updater still don't offer me an update and I don't want to switch to the beta channel, since my NC installation contains valuable data.

**Comment by annando** [comment]
I now was able to test it. This seems to work great.
