### ISSUE TITLE
Handles in Global timeline not correctly linked

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#253]
Check out this example where @blizzz is on a different instance:
![nextcloud social global timeline](https://user-images.githubusercontent.com/925062/50293327-9f303e80-0473-11e9-918b-fb0b51072570.png)

The handles he mentions should be correctly highlighted and linked to their respective accounts. It should also always be the short handle and not show the other person’s server in the message.

**Comment by daita** [comment]
FYI: the quotes are better managed in 0.1.1: https://github.com/nextcloud/social/pull/255

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/social/pull/382
