### ISSUE TITLE
Emojis locally display as ????, fine on remote site 

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/social#276]
**Emojis display as ????  locally**
I am able to see an emoji fine when composing, however after posting the local display shows ????.
When looking at the same post from https://mastodon.social (after subscribing to the Nextcloud user), its shows up fine.

**To Reproduce**
1. Post from your Nextcloud social app. While writing, the emoji shows up fine.
2. Click on "Post...", the post will show up locally with ???? for emojis, the emoji will show up fine in the remote user timeline.

**Expected behavior**
Show emoji graphically on both ends.

**Screenshots**

![selection_158](https://user-images.githubusercontent.com/317514/50402512-3d1e5480-0765-11e9-87a9-b63b1a5cdd0e.png)

![selection_159](https://user-images.githubusercontent.com/317514/50402518-43143580-0765-11e9-8c47-5f7abfa6068f.png)

**Client details:**
 - OS: Debian 9 (Stretch)
 - Browser Firefox 60.4.0esr
 - Version Nextcloud 15

**Comment by juliushaertl** [comment]
@MagicFab What database are you using for Nextcloud? In case it's mysql/mariadb please check if there support for 4-byte characters: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by juliushaertl** [comment]
@jancborchardt Let's just assign a milestone and to develop label if we can reproduce. :wink:

**Comment by daita** [comment]
I had the same issue, the link you gave fixed it !

**Comment by MagicFab** [comment]
Glad someone could confirm, I can't test this anymore but if I may make a suggestion, please do add a note to release notes of this app about it. I vaguely remember reading about this in the very detailed (and long) installation guides but it would be very helpful to have it in the app release notes/REAME directly.
