### ISSUE TITLE
Please implement support for Blind Key Rotation (privacy feature)

### ISSUE THREAD

**Issue by kaniini** [nextcloud/social#286]
**Is your feature request related to a problem? Please describe.**

At present, Nextcloud Social implements support for JSON-LD Linked Data Signatures.  This is problematic for a few reasons, mostly relating to future deniability due to their irrevocable nature.  A mitigation for the loss of deniability is Blind Key Rotation.

**Describe the solution you'd like**

Implementing support for Blind Key Rotation is quite simple: if a signature fails to validate, re-fetch the actor keys once and only once, then check the signature again.

Similarly, for Nextcloud Social to implement the other side of Blind Key Rotation is also simple: if an actor deletes an item, send the `Delete` out normally (signing it with the original key), then change the keys without sending an `Update` message.  The key will be rotated the next time the actor publishes a message as his followers' instances fetch the new public key.

This is also useful for handling an edge case where an instance is reinstalled.

**Describe alternatives you've considered**

An alternative would be to only support HTTP Signatures (which is fully compatible with Mastodon and implemented by essentially every other fediverse software) which trades an irrevocable, permanent signature for one which is detached and only exists in a given moment.

However, even in a world where only HTTP Signatures are supported, Blind Key Rotation is still useful for the event where a message (and it's headers) are intercepted.  This is, of course, unlikely with proper TLS usage, but still worth considering.

**Comment by daita** [comment]
I understand the concept of refreshing the key from a remote account in case of failure during the verification process.
I don't get why I should refresh the keys when a user delete an item.

**Comment by kaniini** [comment]
Refreshing the keys after a delete improves deniability.

**Comment by daita** [comment]
@kaniini Thanks !

I will definitively implement this.
It seems that I just need to define a lifespan to a key, I do not need to refresh it after specific actions ?

**Comment by jancborchardt** [comment]
@daita 0.1.2 should be for bugfixes though ;) If new features start being implemented, let’s release 0.1.2 and start on 0.2?

**Comment by daita** [comment]
Totally agree, however implementation is quick and simple and can be done while I am waiting for PR to be reviewed!
