### ISSUE TITLE
Ignores "Accept: application/activity+json", breaking federation

### ISSUE THREAD

**Issue by lanodan** [nextcloud/social#287]
**Describe the bug**
Fetching the profile with ``Accept: application/activity+json`` in the headers seems to be ignored, at least on the profile.
Related pleroma issue: https://git.pleroma.social/pleroma/pleroma/issues/488

**To Reproduce**
- ``curl https://cloud.beepboop.ga/apps/social/@dirb/ -H 'Accept: application/activity+json'``

**Expected behavior**
A ActivityPub object should be returned, as expected, or an error, never a HTML page.

**Server details**
Not my instance, and I have no knowledge about nextcloud and there is no nodeinfo. So this is why I even put the URL to the profile.

**Comment by lanodan** [comment]
I looked a bit in the code, done few tests and it looks you’re doing the match for ActivityPub with `application/ld+json` which is the JSON-LD MIME type that is usually used for `@context` resolving. Might be why it works for mastodon but is basically broken everywhere else.

See: https://github.com/nextcloud/social/blob/c6943191f9abe9b88cdee313202a2c56fd315310/lib/Controller/ActivityPubController.php#L329

**Comment by daita** [comment]
Also 

https://github.com/nextcloud/social/blob/c6943191f9abe9b88cdee313202a2c56fd315310/lib/Controller/ActivityPubController.php#L329

**Comment by juliushaertl** [comment]
Fixed with #290
