### ISSUE TITLE
Fetching status id gives non-ActivityPub data

### ISSUE THREAD

**Issue by lanodan** [nextcloud/social#296]
**Describe the bug**
Fetching a status by it’s id gives non-ActivityPub data.

**To Reproduce**
1. Get a Nextcloud status id/url. Here I’ll take <https://cloud.beepboop.ga/apps/social/@dirb/15464603731806653100>)
2. Request it with ``Accept: application/activity+json``. Here: ``curl -H 'Accept: application/activity+json' https://cloud.beepboop.ga/apps/social/@dirb/15464603731806653100``

**Expected behavior**
The ActivityPub object should be returned (see the specification or other ActivityPub software).

**Server details**
Not my instance, and I have no knowledge about nextcloud and there is no nodeinfo. So this is why I even put the URLs.

**Comment by daita** [comment]
please try with `Accept: application/ld+json` or wait for 0.1.2: https://github.com/nextcloud/social/pull/290/files

**Comment by dirb** [comment]
I'm the owner of that box, it's ruining on:
PHP 7.2.10-0ubuntu0.18.04.1
Nextcloud 15.0.0
nextcloud/social 65dc245807dbdab34b716e602497848248f9e896

so the ["compare Accept Header from a list"](https://github.com/nextcloud/social/pull/290/files) is pull request already merged

**Comment by lanodan** [comment]
Sorry, I should have noted that I did try with `application/ld+json` so it’s not a duplicate.
