### ISSUE TITLE
Diaspora will not support ActivityPub soon

### ISSUE THREAD

**Issue by annando** [nextcloud/social#329]
The app description says ```🙋 Find your friends: No matter if they use Nextcloud, 🐘 Mastodon, 🇫 Friendica, and soon ✱ Diaspora, 👹 MediaGoblin and more – you can follow them!```

It is very unlikely that Diaspora will support ActivityPub in a foreseen amount of time. See the discussion here: https://github.com/diaspora/diaspora/issues/7422

I suggest to remove any reference to Diaspora.

**Comment by annando** [comment]
Problem is that already there had been some confusion at people thinking that they can now connect to Diaspora with it. So especially non-developers are confused by now.

The core developers had been clear about ActivityPub and Diaspora. They said that none of their core developers will work at it. The only possibility currently seems to be that some new contributor would invest time to work at it.

So especially this "soon" will not happen soon. A "Possibly at some time Diaspora will support AP" would be much more honest.

**Comment by juliushaertl** [comment]
I am with @annando here, we should not advertise integration that is most likely not going to happen anytime soon.

**Comment by jancborchardt** [comment]
Ok, good point then. :) Do you also know about the status with MediaGoblin? Because then we could adjust both to our best knowledge.

**Comment by zcdunn** [comment]
The [latest mention ](https://mediagoblin.org/news/tpac-2016-and-review-activitypub.html) of ActivityPub on MediaGoblin's website is from 2016. cwebber, the lead dev, has mentioned on the fediverse that they are working on other stuff recently

**Comment by annando** [comment]
I know MediaGoblin only by name, but I don't have any contact to the developers (in difference to Diaspora).

Concerning AP and Diaspora I just had a talk with some new coder at the project. He will work at many different stuff at Diaspora and only after this all had been done he will be able to focus on AP - so I guess that the most early date to start would be somewhere around 2020. But since Diaspora isn't yet multi protocol enabled and the frontend lacks some functionality that would be needed, this will be several months of work, possibly even a year.

**Comment by HankG** [comment]
> Concerning AP and Diaspora I just had a talk with some new coder at the project. He will work at many different stuff at Diaspora and only after this all had been done he will be able to focus on AP - so I guess that the most early date to start would be somewhere around 2020...

I wouldn't bank on it happening at production quality code in 2020 either...it's a nice thought though...it also would probably be as an extension not in the core so I'm not even sure how that would be mentioned even once it is a thing. :)

**Comment by jancborchardt** [comment]
What do you think about this:

> 🙋 Find your friends: No matter if they use [☁ Nextcloud Social](https://github.com/nextcloud/social#nextcloud-social), [🐘 Mastodon](https://joinmastodon.org), [🇫 Friendica](https://friendi.ca), [📺 PeerTube](https://joinpeertube.org), [🅿️ Pleroma](https://pleroma.social) or [📷 PixelFed](https://pixelfed.org) – you can follow them! (Hopefully [✱ Diaspora](https://diasporafoundation.org), [👹 MediaGoblin](https://mediagoblin.org) and more will support [ActivityPub](https://en.wikipedia.org/wiki/ActivityPub) soon too!)

**Comment by annando** [comment]
@HankG is the one who will likely implement AP in Diaspora. And you saw what he wrote. He even sees it realistic that AP in Diaspora wouldn't be productive before 2021.

**Comment by jancborchardt** [comment]
Ok, so then just:

> > 🙋 Find your friends: No matter if they use [☁ Nextcloud Social](https://github.com/nextcloud/social#nextcloud-social), [🐘 Mastodon](https://joinmastodon.org), [🇫 Friendica](https://friendi.ca), [📺 PeerTube](https://joinpeertube.org), [🅿️ Pleroma](https://pleroma.social) or [📷 PixelFed](https://pixelfed.org) – you can follow them!

(Because we already mention ActivityPub in another point below.)

**Comment by jancborchardt** [comment]
Pull request at https://github.com/nextcloud/social/pull/367, please review! :slightly_smiling_face:
