### ISSUE TITLE
Content HTML is not interpreted correctly

### ISSUE THREAD

**Issue by annando** [nextcloud/social#331]
**Describe the bug**
Links from Friendica are interpreted wrongly. 

**To Reproduce**
* Create a post in Friendica that contains a link
* Send it to a Nextcloud Social account

**Expected behavior**
The link should be accessible.

**Screenshots**
![bildschirmfoto 2019-01-13 um 17 15 42](https://user-images.githubusercontent.com/844208/51087699-e77f0b80-1756-11e9-9339-4822cb0ce600.png)
![bildschirmfoto 2019-01-13 um 17 16 36](https://user-images.githubusercontent.com/844208/51087714-09788e00-1757-11e9-9ebd-4f8828d33382.png)

**Comment by WNYmathGuy** [comment]
Just to add a little here, 
```
Another try @me@my.domain.com [i]Let's see[/i] if [b]this[/b] is on your timeline.
```
never made it from Friendica to Nextcloud, but ...
```
Another try @me@my.domain.com Let's see if this is on your timeline.
```
did make it from Friendica to Nextcloud.

On a happy note though, public posts on Friendica do propagate over once the follow relationship is made in Nextcloud.

**Comment by juliushaertl** [comment]
Let's keep track of that in #328, which addresses the same :wink:
