### ISSUE TITLE
following / followers counter not working properly

### ISSUE THREAD

**Issue by Lurkars** [nextcloud/social#333]
The following and followers counter in profile view is not updating after follow and following events.

1. Search for account to follow
2. Click on 'Follow'
3. Go to your Profile 
4. Following count not incremented

In a first test, re-login corrected the counter, but cannot reproduce, so behavior seems a bit random.

_nc: 15.0.2
social: 0.1.2
ubuntu 18.04, apache 2.4_

**Comment by daita** [comment]
This information is cached and updated every tick of the cron setup for your nextcloud (should be 15 minutes)

**Comment by Lurkars** [comment]
Ok, that explained my "random" feeling. (cron is on 15 minutes)
Nevertheless I think it is a bit counterintuitive, especially when you begin with 0 Following, start following some people and don't get direct feedback. That is the first thing people do with this and so for me it was the first thing to report a bug, because 0 Following was displayed when I actually got some.
So should I create a Feature Request now or is the AJAX background job recommend as default for this?

**Comment by juliushaertl** [comment]
@daita Maybe we can just update the following count for the current user if you follow someone. That shouldn't be much overhead actually.

**Comment by daita** [comment]
Did something like this yesterday, i'll check and push today

**Comment by daita** [comment]
should be implemented in 0.2.0: #340
