### ISSUE TITLE
Roadmap/Goals?

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/social#347]
I hope I didn't miss it, but is there some kind of roadmap or a list of goals for the Social app? If not, I'd like to open some kind of discussion about the topic, because I've got a few questions.

As far as I know the Social app implements the ActivityPub protocol which means - in theory - it could work as an (more or less complete) replacement for, e.g., Mastodon (when I say replacement I mean I don't have to setup my own Mastodon instance because I could just use Nextcloud with the Social app).

This would also open up the possibility to allow clients which speak the ActivityPub protocol (e.g. Tusky, Mastalab, Twidere, AndStatus, etc.) to connect to a Nextcloud instance (which would be awesome).

Or was the idea behind the Social app to be used between Nextcloud users and support for other Instances through the ActivityPub protocol (e.g. Mastodon) was just a coincidence? On the other hand, that wouldn't really make sense, because we have Nextcloud Talk and Circles for that, right?

**Edit**: I just found issue #145. So, I guess it could really act as a replacement for standalone Mastodon servers?

**Comment by jospoortvliet** [comment]
I can recommend to look at the milestones: https://github.com/nextcloud/social/milestones

That's essentially the current roadmap.

it is indeed true that Nc is a ActivityPup server able to connect to Mastodon servers and federate with others who have implemented this API.
