### ISSUE TITLE
Timeline(s) failing to update

### ISSUE THREAD

**Issue by imattau** [nextcloud/social#349]
Timeline(s) have stopped loading new entries. Failing to refresh.

**To Reproduce**
1. Go to any timeline.

**Expected behavior**
New 'toots' expected to appear

**Client details:**
 - OS: Android
 - Browser Firefox
 - Version 64
 - Device: Samsung Tablet S4 & Note 8

<details>
<summary>Server details</summary>

**Social app version:**
0.1.2
**Operating system**:
Linux
**Web server:**
Apache
**Database:**
Mysq
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
15.0.2
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No errors or warnings display
```

</details>

**Comment by daita** [comment]
might be related to #412.

**Comment by daita** [comment]
is it still relevant ?
