### ISSUE TITLE
Profile page doesn't work if /.well-known/webfinger is a redirection

### ISSUE THREAD

**Issue by sim6** [nextcloud/social#369]
**Describe the bug**
Error loading Profile page if /.well-known/webfinger is a redirection.

**To Reproduce**
1. Configure a redirection from /.well-known/webfinger to the nextcloud endpoint.
1. Go to Social app.
2. Click on Profile.
4. See error "Failed to load account details sim6@probeta.net"

<details>
<summary>Server details</summary>
**Social app version:** 0.1.3 

**Operating system**: debian

**Web server:** apache2

**Database:**  mariadb

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
{"reqId":"XEeGrH8AAAEAAC2xxOYAAAAC","level":1,"time":"2019-01-22T21:10:04+00:00","remoteAddr":"185.107.106.105","user":"sim6@probeta.net","app":"social","method":"GET","url":"\/nextcloud\/index.php\/apps\/social\/api\/v1\/global\/account\/info?account=sim6@probeta.net","message":"[>>] request: {\"host\":\"probeta.net\",\"url\":\"\\\/.well-known\\\/webfinger\",\"timeout\":10,\"type\":0,\"data\":{\"resource\":\"acct:sim6@probeta.net\"}} - result: <!DOCTYPE HTML PUBLIC \"-\/\/IETF\/\/DTD HTML 2.0\/\/EN\">\n<html><head>\n<title>302 Found<\/title>\n<\/head><body>\n<h1>Found<\/h1>\n<p>The document has moved <a href=\"https:\/\/probeta.net\/nextcloud\/public.php?service=webfinger\">here<\/a>.<\/p>\n<hr>\n<address>Apache\/2.4.25 (Debian) Server at probeta.net Port 443<\/address>\n<\/body><\/html>\n","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.2.0"}
{"reqId":"XEeGrH8AAAEAAC2xxOYAAAAC","level":3,"time":"2019-01-22T21:10:04+00:00","remoteAddr":"185.107.106.105","user":"sim6@probeta.net","app":"index","method":"GET","url":"\/nextcloud\/index.php\/apps\/social\/api\/v1\/global\/account\/info?account=sim6@probeta.net","message":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Social\\Service\\CurlService::getArray() must be of the type array, null given, called in \/var\/www\/nextcloud\/apps\/social\/lib\/Service\/CurlService.php on line 124","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/social\/lib\/Service\/CurlService.php","line":124,"function":"getArray","class":"OCA\\Social\\Service\\CurlService","type":"->","args":["links",null]},{"file":"\/var\/www\/nextcloud\/apps\/social\/lib\/Service\/CacheActorService.php","line":204,"function":"retrieveAccount","class":"OCA\\Social\\Service\\CurlService","type":"->","args":["sim6@probeta.net"]},{"file":"\/var\/www\/nextcloud\/apps\/social\/lib\/Controller\/LocalController.php","line":491,"function":"getFromAccount","class":"OCA\\Social\\Service\\CacheActorService","type":"->","args":["sim6@probeta.net"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"globalAccountInfo","class":"OCA\\Social\\Controller\\LocalController","type":"->","args":["sim6@probeta.net"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Social\\Controller\\LocalController"},"globalAccountInfo"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Social\\Controller\\LocalController"},"globalAccountInfo"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Social\\Controller\\LocalController","globalAccountInfo",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"social.Local.globalAccountInfo"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"social.Local.globalAccountInfo"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"social.Local.globalAccountInfo"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/social\/api\/v1\/global\/account\/info"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/social\/vendor\/daita\/my-small-php-tools\/lib\/Traits\/TArrayTools.php","Line":188,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.2.0"}
</details>

**Comment by daita** [comment]
Can you paste your configuration regarding the redirection ?

**Comment by daita** [comment]
can you try this:
```
SSLProxyEngine On                                                                                                                                                                
ProxyPass /.well-known/ https://test.pontapreta.net/nextcloud/.well-known/                                                                                                           
ProxyPassReverse /.well-known/ https://test.pontapreta.net/nextcloud/.well-known/                
```

**Comment by daita** [comment]
those lines needs to be in the Apache config file of your website, within the `<VirtualHost>`

**Comment by WanTanFao** [comment]
Is there a way to handle this within .htaccess?

Got the following rules enabled on irgendwo.co to use irgendwo.co as my federation domain while serving neuland.irgendwo.co as Mastodon frontend:

`<IfModule mod_rewrite.c>
	RedirectMatch ^/.well-known/host-meta$ https://neuland.irgendwo.co/.well-known/host-meta

	Redirect /.well-known/webfinger https://neuland.irgendwo.co/.well-known/webfinger

</IfModule>`

This works well if I try to lookup something (irgendwer@irgendwo.co) from a different Mastodon instance, but Nextcloud seems to not like the redirection.

But I'm limited to .htaccess with no access to the VirtualHost config in this specific case.

**Comment by susobaco** [comment]
> those lines needs to be in the Apache config file of your website, within the `<VirtualHost>`

Adding those lines configured for my server in /etc/apache2/sites-available/nextcloud.conf inside the <Virtualhost> section I still have the same error message:

500 - {"status":-1,"exception":"OCA\\Social\\Exceptions\\RequestContentException","message":"404 - {\"host\":\"palautgn.duckdns.org\",\"url\":\"\/.well-known\/webfinger\",\"timeout\":10,\"type\":0,\"data\":{\"resource\":\"acct:admin@******.duckdns.org\"}}"}

**Comment by daita** [comment]
@WanTanFao you're right: currently Nextcloud Social will not allow a 302 (Redirection) this is why Rewrite is better. 

I will implement this in 0.2.0

**Comment by sim6** [comment]
Thank you very much!
