### ISSUE TITLE
every page is blank except profile

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/social#373]
I've installed social and reset it a few times using occ but every page is blank except for the profile page. nothing in the error logs, it just seems to do nothing.

NC 15.0.2
Social 0.1.3

If a write a post and send it, it seems to go somewhere but it's not visible on any of the pages.
![image](https://user-images.githubusercontent.com/1305249/51652526-afd85500-1fdb-11e9-9b04-af3617819d4d.png)

**Comment by daita** [comment]
can you search for a remote account ? can you search for a local account from a remote instance of mastodon ?

**Comment by dgferrin** [comment]
Same problem here, but solved it clearing caché from browser, now it works fine.

**Comment by lachlan-00** [comment]
Clearing cache gives me the pages and the test posts are apparently there now.

If i go to another federated mastadon should i be able to find my @user@server?

**Comment by juliushaertl** [comment]
@lachlan-00 Did you have a previous version of social installed before 0.1.3, so that there could be outdated js files in the cache?

**Comment by emersonkfuri** [comment]
> @lachlan-00 Did you have a previous version of social installed before 0.1.3, so that there could be outdated js files in the cache?

That happened to me! I had 0.1.2 and only after clearing my browser cache, I was able to proper load the app.
