### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by daita** [nextcloud/social#4]
How to manage federation ?

- Admin add federated instance of Nextcloud to a list
- every one can federated and share
- both with option

**Comment by schiessle** [comment]
I think by default we should allow to follow everyone on every server. But imho there should be a admin setting to limit it to users on the server only so that you can also use it as an internal social network for your organization only.

**Comment by jancborchardt** [comment]
@schiessle yes, that's the simple first step setting. But it is also necessary to have the ability to be part of the federation while still having a blocklist for specific servers, e.g. if they carry hateful or illegal content.

**Comment by daita** [comment]
done in alpha 2.0
