### ISSUE TITLE
navigation not rendered on master

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/social#408]
**Describe the bug**
on master branch I see an empty navigation area (at the left) and an error in the console:
```
[Vue warn]: Unknown custom element: <app-navigation-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App> at src/App.vue
       <Root> 5 vue.esm.js:610
warn27VueJSimage/svg+xml	js main.js:61
Bootstrap3Webpackicon
```
if I checkout the latest tag v0.1.4 and rerun `make build-js` it's working... if I checkout master again and build vue, the error is back...

cc @juliushaertl

**Comment by juliushaertl** [comment]
@violoncelloCH Make sure to run `npm install` since the dependencies have been updated and you need to make sure they get installed on your local installation.

**Comment by juliushaertl** [comment]
Note you will probably need to run npm install everytime you switch between any v0.1.x branch and master, since dependencies have changed there as well.

**Comment by violoncelloCH** [comment]
ahh, thank you @juliushaertl ...
it's working again... didn't knew a npm install was necessary, thought a rebuild would be sufficient...
