### ISSUE TITLE
nextcloud + docker + social => not work

### ISSUE THREAD

**Issue by cedjo** [nextcloud/social#480]
cannot follow or be followed.

when doing this:

`curl https://nc.virtualconfusion.net/.well-known/webfinger?resource=acct:cedric@nc.virtualconfusion.net`

I received this:
`{"subject":"acct:cedric@nc.virtualconfusion.net","links":[{"rel":"self","type":"application\/activity+json","href":"https:\/\/nc.virtualconfusion.net\/apps\/social\/@cedric"}]}`

when doing this:
`curl -H "Accept: application/ld+json" -X GET https:\/\/nc.virtualconfusion.net\/apps\/social\/@cedric`

I receive this:
`{"@context":["https:\/\/www.w3.org\/ns\/activitystreams","https:\/\/w3id.org\/security\/v1"],"id":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric","type":"Person","url":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric","local":true,"aliases":["@cedric","users\/cedric"],"preferredUsername":"cedric","name":"","inbox":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric\/inbox","outbox":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric\/outbox","account":"cedric@nc.virtualconfusion.net","following":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric\/following","followers":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric\/followers","endpoints":{"sharedInbox":"https:\/\/nc.virtualconfusion.net\/index.php\/apps\/social\/inbox"},"publicKey":{"id":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric#main-key","owner":"https:\/\/nc.virtualconfusion.net:6443\/apps\/social\/@cedric","publicKeyPem":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA96yrwXNlHZl7z3V75HJu\nDbgnRRJwsnELiTjCh022Qh\/QLgwQpPhrtBU+mV9Y4rqYffqBokdinxuR8cGz0mYc\nyhl5IvtKszGCezVS7lmeOMCuA02r7+PDDsrapO5hKmwPRKnnbPRqVI2aL4ie9OxH\nCy3xqwe5t0LMN1feqmD7bgK5Ncvf6qMninjRdsjFZjuosJ+8N7ysRRanq2l2qOkd\nADhX\/Z3dcJDAmAL1BS15IVyUv\/LSTBYH2qS54hZWaQBg7eTTSZW+3iuCi6lpceLm\n\/mKjz8qkCwj6ClQjylk5djZUXYBr+x4B1eGRAWNoP41q7cOGxP9q9YJswhMcKiog\n2QIDAQAB\n-----END PUBLIC KEY-----\n"}}`

No idea where this port 6443 is there.

I did try: docker exec --user www-data 4b2f62aac223 php ./occ social:reset

but still same result. any idea?

nextcloud 15.0.5
social 0.1.4

Thanks.

**Comment by cedric** [comment]
Ha, the `@cedric` in your URLs trigger a notification for me. :) Maybe use the "insert code" tags? No biggie.

**Comment by cedjo** [comment]
> 
> 
> Ha, the `@cedric` in your URLs trigger a notification for me. :) Maybe use the "insert code" tags? No biggie.

Can you explain more? I did not follow you. thanks

**Comment by cedric** [comment]
Your comment includes code and commands that have `@cedric` in it. Since it's just entered as text, Github will alert the user with the **@cedric** username. If you use the backticks around your code, then they display it as code and also don't send notifications for Github usernames.

**Comment by cedjo** [comment]
> 
> 
> Your comment includes code and commands that have `@cedric` in it. Since it's just entered as text, Github will alert the user with the **@cedric** username. If you use the backticks around your code, then they display it as code and also don't send notifications for Github usernames.

got you, sorry for this.

**Comment by cedjo** [comment]
I solved the issue with DB clean-up:

`delete from oc_social_server_actors where id='https://nc.virtualconfusion.net:6443/apps/social/@cedric';`
