### ISSUE TITLE
Ostatus Protocol Support

### ISSUE THREAD

**Issue by sunjam** [nextcloud/social#499]
Ostatus, [as referenced here](https://github.com/nextcloud/social/issues/268), pre-dates ActivityPub and is supported by major projects like Mastodon and Pleroma as a sort of federation fallback.  Others can likely provide more details.

**Comment by daita** [comment]
Some functionality of Ostatus are now implemented in the alpha2. I think those implemented functionality are enough. 

If anything is needed, please provide more details !
