### ISSUE TITLE
Post count on public page includes private posts

### ISSUE THREAD

**Issue by shtrom** [nextcloud/social#500]
**Describe the bug**
On a fresh account, I have posted 4 message to my followers, and 2 to the public. The public page when not logged in shows both public posts, but confusingly still indicates that I have a total of 6 posts.

**To Reproduce**
1. Post a message to followers
2. Post a message to the public
3. Log out and go to the public profile
4. See only the public message, but the post count says “2 posts”

**Expected behavior**
The post count should say “1 post”

**Screenshots**

**Client details:**
 - OS: ArchLinux
 - Browser Firefox
 - Version 66.0.3
 - Device: desktop

**Social app version:**  0.1.4

**Operating system**: OpenBSD 6.4

**Web server:** Apache 2.24

**Database:** MySQL

**PHP version:** 7.2.x

**Nextcloud version:** 15.0.5

**Comment by daita** [comment]
fixed in alpha2
