### ISSUE TITLE
Support for host-meta

### ISSUE THREAD

**Issue by r3pek** [nextcloud/social#505]
**Is your feature request related to a problem? Please describe.**
Support to have the federated domain be different from the domain where nextcloud is published.

**Describe the solution you'd like**
Mastodon supports this using the [host-meta](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md#webfinger). One can have a user named @r3pek@nakeddomain.com and nextcloud published on nc.nakeddomain.com
Remeber: NC should **only** be available at nc.nakeddomain.com.

**Describe alternatives you've considered**
I tried hard coding the host-meta file on the naked domain webserver but looks like some other backend changes are needed since  I got some requests to the webserver running on the naked domain that shouldn't go there.

**Additional context**
Well, the Mastodon link above shows exactly what's needed and how it (is supposed to) works. I do have it running this way on my Mastodon instance, but if I could keep everything on NC itself, better :)

**Comment by daita** [comment]
This is something to be implemented in the core, not in the social app. Not sure I have time for NC17, maybe 18

**Comment by r3pek** [comment]
@daita shouldn't be too hard to implement since there should be some kind of infrastructure in place. If you could point me to where it should be implemented, i may try to help out.

**Comment by daita** [comment]
You can have a look to `lib/webfinger.php` in the social app.
The file is called by core on webfinger request:
>      `./occ config:app:get core public_webfinger`
For the host-meta, you will need to create a new file there and setup this way: 
>       `./occ config:app:set --value 'social/lib/host-meta.php' core public_host-meta`

Some links:
- https://github.com/nextcloud/server/blob/master/.htaccess#L46-L48
- https://github.com/nextcloud/social/blob/ec822a440bbc9b81005921c6430640d5388e5289/lib/Service/AccountService.php#L218

**Comment by daita** [comment]
feature released in 0.2.5

**Comment by r3pek** [comment]
@daita for some strange reason, it still doesn't work :( (i might actually be missing something)
When I use occ social:reset, what URL should I use?

**Comment by daita** [comment]
The URL in social should be the url from the cloud.

To enable host-meta on apache (on your alias):

```
  RedirectPermanent /.well-known/host-meta http://cloud.example.net/.well-known/host-meta
```
 and run the occ command:

>      ./occ config:app:set -value 'example.net' social social_address
