### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/social#519]
**Is your feature request related to a problem? Please describe.**

I do not want to rush you, but would it be possible to release a new version?

The [last version](https://github.com/nextcloud/social/releases/tag/v0.1.4) was released some time ago (on 9 Feb) and there are already many nice features done in the [0.2 milestone](https://github.com/nextcloud/social/milestone/2?closed=1).

I am just curious about what is stopping the new release. Nevertheless, thanks for your work!

**Describe the solution you'd like**

Release a new version if it is possible.

**Describe alternatives you've considered**

I can run the code from the master branch but I am scared about the data migrations. (Some UI glitches are not a problem, but I do not want to loose some data.)

**Comment by jancborchardt** [comment]
@daita could you push a new version? :)

**Comment by daita** [comment]
alpha2 is almost ready, the core structure looks stable and data migrations should be good enough (also migration does not delete old tables; the deletion will be done in further release of alpha2 if there is no complains). 

The release is blocked by some task on the front-end, and I am not good at Vue... if anyone of you is willing to have a look and help on this, do not hesitate to ask and/or pull !

Let's make the list of what needs to be done for alpha2:

- [ ] Displaying SocialAppNotifications. [1]
- [ ] Displaying Announce/Boost. [2]
- [ ] Displaying Replied-To Post. [3]
- [x] filters some items from Stream based on 'hidden_on_timeline' (backend, working on it myself) 
- [ ] move the SocialAppNotifications from the Direct stream to a Notifications stream  (@juliushaertl  should be able to quickly add the stream)
- [ ] add the time to the SocialAppNotifications items (back end, working on it)
- [ ] remove SocialAppNotifications on Unfollow (backend, working on it myself)


Those are the JSON sent back by the backend:

[1] SocialAppNotifications are items available in the 'Direct' timeline, and will be moved to a specific timeline (Notifications). The item displays message, notifications-like when someone is following you:
![Selection_042](https://user-images.githubusercontent.com/1038617/57931985-ebf03800-78a0-11e9-9e4f-e000ed11327e.png)

[2] Announce should displays the boosted message (available in the cache entry) with a message in the header saying 'actor boosted ..' (using actor_info):
![Selection_043](https://user-images.githubusercontent.com/1038617/57956566-90de3580-78e0-11e9-9ff0-c65ef0bb6c5d.png)

[3] _needed to be defined_


Please, @juliushaertl @violoncelloCH or anyone willing to help on the front-end part !

**Comment by violoncelloCH** [comment]
I'll try to find some time during the next two weeks to do [2]... :)

**Comment by lachmanfrantisek** [comment]
@daita Thank you for the response.

> alpha2 is almost ready, the core structure looks stable and data migrations should be good enough (also migration does not delete old tables; the deletion will be done in further release of alpha2 if there is no complains).

I'll try to test it. Thanks!

> The release is blocked by some task on the front-end, and I am not good at Vue... if anyone of you is willing to have a look and help on this, do not hesitate to ask and/or pull !

I am more a python guy, so I am not sure if it would be useful. Maybe a challenge for me to learn some php/vue stuff...;-)

> Let's make the list of what needs to be done for alpha2:

You can probably move some issues from [milestone 2](https://github.com/nextcloud/social/milestone/2) to see what's really missing for the final release...


Thank you for all your work!

**Comment by daita** [comment]
@nextcloud/vue anyone ?!

**Comment by daita** [comment]
thanks to @violoncelloCH for the work on Announce/Boost !

**Comment by lachmanfrantisek** [comment]
I think you've already released a new version..;-) Thanks for it.
