### ISSUE TITLE
F5 on /apps/social/timeline forwards to /apps/files/

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/social#566]
### Steps to reproduce
1. Open the home page of the social app
2. Press `F5` (or `Ctrl`+`F5`)

### Expected behaviour
Refresh the current page.

### Actual behaviour
Forwards to Files app.

## Server configuration detail

**Operating system:** Linux 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64

**Webserver:** nginx/1.15.12 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit

**PHP version:** 

7.3.5
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, imagick, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** hoellen/nextcloud docker image

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - audioplayer: 2.7.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - camerarawpreviews: 0.7.0
 - carnet: 0.16.1
 - circles: 0.17.3
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.1
 - cospend: 0.1.0
 - data_request: 1.3.0
 - dav: 1.9.2
 - deck: 0.6.2
 - drawio: 0.9.3
 - drop_account: 0.1.0
 - dropit: 0.2.1
 - event_update_notification: 0.3.4
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_3d: 0.1.0
 - files_downloadactivity: 1.5.0
 - files_external: 1.7.0
 - files_linkeditor: 1.0.10
 - files_markdown: 2.0.6
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.0.4
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - gpxedit: 0.0.11
 - gpxmotion: 0.0.9
 - gpxpod: 3.0.3
 - groupfolders: 4.0.2
 - guests: 1.0.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notes: 2.6.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ownbackup: 19.5.0
 - password_policy: 1.6.0
 - passwords: 2019.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - qownnotesapi: 19.4.0
 - quota_warning: 1.5.0
 - ransomware_detection: 0.5.1
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - registration: 0.4.6
 - richdocuments: 3.3.8
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - sharerenamer: 2.6.0
 - social: 0.2.2
 - spreed: 6.0.1
 - survey_client: 1.4.0
 - suspicious_login: 1.0.0
 - systemtags: 1.6.0
 - tasks: 0.10.1
 - telephoneprovider: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 3.0.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - checksum
 - deck.old
 - encryption
 - end_to_end_encryption
 - phonetrack
 - social-0.2.2
 - social2
 - support
 - twofactor_admin
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "beta.scoutcloud.tk",
        "beta.lachman.tk"
    ],
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbtype": "pgsql",
    "version": "16.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "logdateformat": "Y-m-d H:i:s",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Operating system:** Linux - Fedora Workstation 30 (Gnome)

## Logs

<details><summary>Web server error log</summary>

```
I did not see anything related.
```
</details>

<details><summary>Nextcloud log</summary>

```
I did not see anything related.
```
</details>

<details><summary>Browser log</summary>

I did not see anything related.
</details>

**Comment by daita** [comment]
Thanks for your report !

**Comment by lachmanfrantisek** [comment]
Tested the master and works well. Thanks for the fix.

**Comment by lachmanfrantisek** [comment]
@daita After some testing I am not sure about the content of the "home" (`/apps/social/timeline`) and "local timeline" (`/apps/social/timeline/timeline`). It looks like they return the same content. (Same image since I have nothing there.)

Is this expected? I can create a new issue, but I am not sure if this is not related to your routing changes...
