### ISSUE TITLE
internal server error after update to 0.2.2

### ISSUE THREAD

**Issue by BrettRD** [nextcloud/social#569]
Loading Social 0.2.2 causes an internal server error.
Nextcloud 15.0.8 installed from ubuntu snap

`QueryException    Could not resolve accountService! Class accountService does not exist`

The error persists when the app is reset via occ,
and persists when the app is removed and reinstalled via the browser

Other info:
Social 0.2.1 was previously installed and suffered from the blank timeline bug but otherwise loaded fine.
My install currently has a warning about a php memory limit.

Error log:

`{"reqId":"8bdPICfmObD2ya5P43x8","level":3,"time":"2019-06-03T12:11:34+00:00","remoteAddr":"XX.XX.XX.XX","user":"XXXXXX","app":"index","method":"GET","url":"\/index.php\/apps\/social\/","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve accountService! Class accountService does not exist","Code":0,"Trace":[{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":119,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["accountService"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["accountService"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":400,"function":"query","class":"OC\\ServerContainer","type":"->","args":["accountService"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":75,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["accountService"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":98,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Social\\Controller\\NavigationController","__class__":"ReflectionClass"}]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":119,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Social\\Controller\\NavigationController"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":426,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Social\\Controller\\NavigationController"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":397,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Social\\Controller\\NavigationController"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/App.php","line":105,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Social\\Controller\\NavigationController"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Social\\Controller\\NavigationController","navigate",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"social.Navigation.navigate"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"social.Navigation.navigate"}]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"social.Navigation.navigate"}]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/social\/"]},{"file":"\/snap\/nextcloud\/13453\/htdocs\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/snap\/nextcloud\/13453\/htdocs\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","Line":104,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.8.1"}`

**Comment by daita** [comment]
Please confirm issue is fixed in 0.2.5

**Comment by BrettRD** [comment]
0.2.5 does indeed fix the error!
Thanks!
