### ISSUE TITLE
Update social 0.2.4 failing

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/social#587]
Just tried to update social to 0.2.4. Update failing due to invalid datetime format. Database is MariaDB 10.3.16

'''HORUS 
Aktualisierung auf 16.0.1
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_social_a2_cache_documts` SET `caching` = ? WHERE `id` = ?' with params ["", "https:\/\/cloud.therapiecenter.org\/documents\/avatar\/88a614ef-99ef-4d53-9f5e-4920fe3c05b9"]: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column `nextcloud`.`oc_social_a2_cache_documts`.`caching` at row 3

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_social_a2_cache_documts` SET `caching` = ? WHERE `id` = ?' with params ["", "https:\/\/cloud.therapiecenter.org\/documents\/avatar\/88a614ef-99ef-4d53-9f5e-4920fe3c05b9"]: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column `nextcloud`.`oc_social_a2_cache_documts`.`caching` at row 3

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.'''

**Comment by daita** [comment]
what was your version of the social app before ?

**Comment by daita** [comment]
Please try 0.2.5

**Comment by Lars1963** [comment]
Version before was 0.2.4

**Comment by Lars1963** [comment]
@daita 
So now I could do some maintenance ;)
I had to disable the app with the occ first. After that I could update the app as usual on the admin page and enable the app afterwards. Seems to be working al fine right now.

As the problem ist solved for me, I'll close the issue
