### ISSUE TITLE
"Failed to load account details user@server.tld"

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/social#592]
**Describe the bug**
After one of the latest upgrades (to v0.2.4 or v0.2.5, not sure, sorry) I'm not able to use the Social App anymore because the following error occurs:

```
Failed to load account details KopfKrieg@absolem.cc
Failed to load more timeline entries
```

The issues #570 and #591 might also be related to this problem. Also, I was affected by a bug in v0.2.1 alredy, maybe this has something to do with it (#558, but this was solved in version 0.2.2).

**To Reproduce**
1. Log in to your Nextcloud
2. Click on the Social App
3. Get a notification on top of the screen with the previously mentioned error message

**Expected behavior**
No error message should appear and everything should be working (e.g. I should be able to see whom I'm following, my followers, my toots, toots from others, etc.).

**Screenshots**
![Bildschirmfoto von 2019-06-24 00-47-41](https://user-images.githubusercontent.com/5047813/59982992-7eab9180-961a-11e9-9d34-5bf61fe98019.png)

**Client details:**
 - OS: Archlinux
 - Browser Firefox
 - Version v67.0.4
 - Device: Lenovo ThinkPad T480

**Server details**
 - Social app version: 0.2.5
 - Operating system: Ubuntu 18.04 LTS
 - Web server: Apache serving Nextcloud with Caddy as proxy
 - Database: PostgreSQL 11.4
 - PHP version: 7.3.6
 - Nextcloud version: 16.0.1.1

**Comment by KopfKrieg** [comment]
Regarding issue #570 I'd like to add the following output:
```
nextcloud=# select * from social_a2_cache_actors;
 id_prim | id | type | account | local | following | followers | inbox | shared_
inbox | outbox | featured | url | preferred_username | name | icon_id | summary 
| public_key | source | details | creation 
---------+----+------+---------+-------+-----------+-----------+-------+--------
------+--------+----------+-----+--------------------+------+---------+---------
+------------+--------+---------+----------
(0 rows)

nextcloud=#
```

Shouldn't there be an entry for my user?

**Comment by daita** [comment]
yes, should be.

please run: `./occ social:cache:refresh`

**Comment by KopfKrieg** [comment]
Purging everything using your post from issue #591 fixed this also. I'll close the issue.
