### ISSUE TITLE
Incorrect Author in home view

### ISSUE THREAD

**Issue by shtrom** [nextcloud/social#594]
**Describe the bug**
Recent posts I wrote (with 0.2.5) appear as authored by a different, remote, user I'm following (but improperly linked as a local one, reminiscent of #585). The same message is, however, shown as properly authored by me in the Local timeline.

**To Reproduce**
1. Go to Home
2. Post a message
3. See message as posted by different user in Home view, but actual author in Local timeline

**Expected behavior**
Message is shown as posted by actual author in all views

**Screenshots**
Correct local timeline
![Screenshot from 2019-06-24 22-43-14](https://user-images.githubusercontent.com/160280/60019667-c8a37e80-96d1-11e9-8839-a8033ac12f03.png)

Incorrect home view
![Screenshot from 2019-06-24 22-43-37](https://user-images.githubusercontent.com/160280/60019668-c8a37e80-96d1-11e9-9004-b346d490112f.png)

**Client details:**
 - OS: ArchLinux x86_64
 - Browser Firefox
 - Version 67.0.3 [Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0]
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:** 0.2.5

**Operating system**: OpenBSD 6.5 GENERIC#3 amd64

**Web server:** Apache/2.4.39 (Unix) LibreSSL/2.9.1 mod_chroot/0.5 (fpm-fcgi)

**Database:** mysql 10.0.38

**PHP version:** 7.3.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, calendar, ctype, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, json, mbstring, session, PDO, bz2, posix, readline, Reflection, standard, SimpleXML, sockets, sodium, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, gd, imagick, intl, ldap, mysqli, pdo_mysql, pspell, redis, tidy, zip, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page) 16.0.0 - 16.0.0.9

</details>

**Comment by r3pek** [comment]
I'm seeing the same behaviour, but nothing shows up on the "Local timeline"

**Comment by daita** [comment]
should be fixed on 0.2.6

**Comment by daita** [comment]
https://github.com/nextcloud/social/releases/tag/v0.2.6

@shtrom if you want to give a try. i'll release it later tonight.

**Comment by r3pek** [comment]
@daita don't know about @shtrom, but on my case, now they don't even show up. Local timeline still empty and "0 posts" on the profile.

**Comment by r3pek** [comment]
actually, and related to the issue i'm commenting on (sorry for the little OT on the previous comment), the @ tags still link to "local" users.

**Comment by daita** [comment]
Do you have any errors in nextcloud log or console?

**Comment by r3pek** [comment]
@daita No errors. My posts does show up on the timeline (not local), if I @ tag someone. posts without tag don't show up at all.
Links to tagged users also still don't work because it thinks they're local (doesn't contain the domain part as Social does when you tag someone).

(if you're around IRC/XMPP we can chat there, which is maybe easier than chatting here :P )

**Comment by daita** [comment]
try to catch me (Cult) on freenode, also; was it working nice on 0.2.5 ?

**Comment by daita** [comment]
seems to be fixed. issue reported by @r3pek is about followers-only post not displayed. will be fixed in 0.2.7

**Comment by shtrom** [comment]
Yup, 0.2.6 seems to work. Cheers!
