### ISSUE TITLE
Cleanly uninstall Social App

### ISSUE THREAD

**Issue by bugspencor** [nextcloud/social#629]
Problems began when I was affected by #558 when upgrading (Nextcloud or Social App, I don't remember). After that I probably never got into a clean Nextcloud state again.

I managed to disable Social and upgrade to a newer release, but when I started Social for a user the page stayed white. So I disabled the app and today I removed it. That looked OK at first.

Today I tried to upgrade Nextcloud from 15.0.8 to 15.0.10. During the update check the updater showed the error:

Check for expected files
The following extra files have been found:
* social

Following advice from https://help.nextcloud.com/t/update-problem-check-for-expected-files-cloud-data/51392 I was moving the "social" folder in the root of the Nextcloud http directory out of the way.

Upgrade then succeeded. When logging in as admin now I could not see the list of installed Apps anymore; the page stays white. In the meantime I restored the snapshot of my virtual machine with Nextcloud 15.0.8 again.

My goal now is to get Nextcloud in a clean working state again, from where I can continue upgrading Nextcloud and maybe start over with social at a later point. So there are some questions:
- How can I remove Social now completely? Where is the social folder in the http-root directory coming from, and how can I resolve the "extra files" issue from above correctly?
- Can the problem that I don't see the list of Apps after upgrading be related to an unclean removal of Social? Where can I get more log information why the app list is not loaded?

If there is more information needed, I can repeat the upgrade process again.

**To Reproduce**
Might be hard to reproduce; I suspect this is a special broken state of my Nextcloud installation. But probably I can repeat and reproduce the upgrade with my Nextcloud VM

**Expected behavior**
- Social App is removed cleanly
- Later Nextcloud maintenance task finish successfully

**Screenshots**

**Client details:**
 - OS: Xubuntu 18.04
 - Browser: Firefox
 - Version:  67.0.4
 - Device: Notebook

<details>
<summary>Server details</summary>

**Social app version:** I don't know the last installed version

**Operating system**: Debian 9

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.0.33

**Nextcloud version:** (see Nextcloud admin page) 15.0.8

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by daita** [comment]
0.2.100 fix this.

**Comment by bugspencor** [comment]
Thanks for the fix!

Just for the record: I reproduced the issue with the empty App page. The resolution was to clear the cache (see https://github.com/nextcloud/server/issues/12507). So maybe not related to the Social App.

**Comment by PeterRob** [comment]
root@hc2-1:/var/www/nextcloud/apps# sudo -u www-data php ../occ social:reset --uninstall
Beware, this operation will delete all content from the Social App.

Do you confirm this operation? (y/N) y
Operation is destructive. Are you sure about this? (y/N) y

Uninstalling Social App...An unhandled exception has been thrown:
TypeError: OC\DB\SchemaWrapper::__construct(): Argument #1 ($connection) must be of type OC\DB\Connection, OC\DB\ConnectionAdapter given, called in /var/www/nextcloud/apps/social/lib/Db/CoreRequestBuilder.php on line 1216 and defined in /var/www/nextcloud/lib/private/DB/SchemaWrapper.php:41
Stack trace:
#0 /var/www/nextcloud/apps/social/lib/Db/CoreRequestBuilder.php(1216): OC\DB\SchemaWrapper->__construct()
#1 /var/www/nextcloud/apps/social/lib/Command/Reset.php(177): OCA\Social\Db\CoreRequestBuilder->uninstallSocialTables()
#2 /var/www/nextcloud/apps/social/lib/Command/Reset.php(129): OCA\Social\Command\Reset->fullUninstall()
#3 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\Social\Command\Reset->execute()
#4 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#5 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#6 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#9 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#10 /var/www/nextcloud/occ(11): require_once('...')
