### ISSUE TITLE
Unliking a post doesn't work

### ISSUE THREAD

**Issue by StCyr** [nextcloud/social#639]
**Describe the bug**
Unliking a post doesn't work

**Comment by daita** [comment]
works good in here, any details on the issue ?

**Comment by StCyr** [comment]
strange: I've just tested the following  using the stCyr_fix640 branch:

1. Like a post (=> the star turns yellow)
2. Got to the 'Liked' view
3. Unlike the post (=> the star turns grey)
4. Switch to the home view
5. See that the star is still yellow here.

There must be some sync' mecanism failing here...

**Comment by daita** [comment]
is it a local post ?

**Comment by StCyr** [comment]
No

**Comment by StCyr** [comment]
But, indeed, the post for which I’ve originally created this issue is a local post (better yet, it’s a post of mine)
