### ISSUE TITLE
New route to get all liked posts

### ISSUE THREAD

**Issue by StCyr** [nextcloud/social#640]
I've implemented recently the front-end for the 'like' functionality, and I think it would make sense to have a navigation menu entry to show all posts ever liked.

I think it first requires a new route to in the backend.

**Comment by daita** [comment]
should be `/api/v1/stream/liked`

Please note that all route for the (local) API will be changed: `/api/v1/` will be changed to `/local/v1/` we will keep /api/v1 available for mastodon client API

**Comment by StCyr** [comment]
This is solved by #642
