### ISSUE TITLE
Error on upgrade to 0.2.100 on PostgreSQL

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/social#662]
Got an error when upgrading to `0.2.100` from `0.2.6` on PostgreSQL.

```
Doctrine\DBAL\Exception\NotNullConstraintViolationException:
An exception occurred while executing 'ALTER TABLE oc_social_a2_cache_documts ADD resized_copy TEXT NOT NULL':
SQLSTATE[23502]: Not null violation: 7 ERROR: column "resized_copy" contains null values
```

I can add more info about my server if it is needed.

**Comment by daita** [comment]
can you empty the entries from the table `oc_social_a2_cache_documts` ?

**Comment by service4me-gk** [comment]
I had the same problem and yes `DELETE FROM oc_social_a2_cache_documts;` did clear the problem for me.

**Comment by warnerbryce** [comment]
Had the same problem : DELETE FROM oc_social_a2_cache_documts; inside psql made the trick. 
Hope it will be modified soon for a fix on the next version.

**Comment by daita** [comment]
should be fixed with 0.2.101

**Comment by service4me-gk** [comment]
On an other installation with PostgreSQL the update to 0.2.101 works without Problem for me.
Thanks for the quick fix;)

**Comment by lachmanfrantisek** [comment]
Upgrade to `0.2.101` works well, thanks!
