### ISSUE TITLE
Not found style for emoji

### ISSUE THREAD

**Issue by deadblackclover** [nextcloud/social#680]
**Describe the bug**
Not found css style for emoji. Picture is big

**To Reproduce**
1. Send status using emoji

**Expected behavior**
Normal size picture

**Screenshots**
![Screenshot at 2019-08-16 08-05-42](https://user-images.githubusercontent.com/26848022/63136708-81fd4100-bffd-11e9-80d8-39ae40a91b32.png)

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 68.0.1
 - Device: notebook

**Comment by StCyr** [comment]
Do you have a 100% reproductibility?

I'm asking because I saw the same behaviour this morning but now my emoji is displayed just fine

**Comment by StCyr** [comment]
I confirm the issue here. But it's transient: it comes and goes. Probably related to some "could not load stylsheet" errors that pop up in my browser (FF also).

![image](https://user-images.githubusercontent.com/8179031/63276048-e7be2700-c2a2-11e9-834a-92cff270bdce.png)

**Comment by StCyr** [comment]
ah! I think I've find a way to make it go away.

I think the issue comes from the fact that the "emoji" class is declared in `Composer.vue`

So, simply loading the "Home" timeline and switching back to "Profile" makes the issue go away

Now, it remains to find out how to fix it in the code :-)

**Comment by daita** [comment]
@nextcloud/vue any idea about this issue ?

**Comment by juliushaertl** [comment]
> I think the issue comes from the fact that the "emoji" class is declared in Composer.vue

Sounds legit, i guess we should have this declaration for the TimelineEntry component as well.

**Comment by StCyr** [comment]
duplicating code?
