### ISSUE TITLE
empty list of followers 

### ISSUE THREAD

**Issue by StCyr** [nextcloud/social#686]
**Describe the bug**

When browsing to https://fqhn/index.php/apps/social/<my_uid>/followers nothing is shown

**Expected behavior**

My followers' list should be shown

**Screenshots**

![image](https://user-images.githubusercontent.com/8179031/63249706-4915d400-c26a-11e9-8909-4eef7b9dc23a.png)

**Possible cause**

I believe this issue is due to `ActivityPubController`'s `followers` method not returning `actor_info` (contrary to its `following` method)

**Comment by daita** [comment]
the table `social_follows` need some purge when an account is deleted

**Comment by StCyr** [comment]
indeed, a `delete from oc_social_a2_follows where actor_id like 'https://mstdn.jp%';` solved my issue

**Comment by StCyr** [comment]
I think other things might need to be deleted because the front-end still shows 6 followers while I've deleted 3 (Yes I know I'm popular :-p )

**Comment by daita** [comment]
do you have a cron running on your Nextcloud ? if not, it might the issue.

Please try : `./occ social:cache:refresh`

**Comment by daita** [comment]
closing this one ?
