### ISSUE TITLE
[Solved] Host Validation Error

### ISSUE THREAD

**Issue by w84death** [nextcloud/social#707]
When I search for kj@nextcloud.p1x.in in Mastodon I get the error. Also my instance do not see anything outside (global timeline). 

My setup:
Internet (SSL) > server with apache proxy (uses domain p1x.in) -> another server with docker IP:9777

1. Go to mastodon.org (or any other)
2. Search for your username
3. See error

![Screenshot from 2019-08-28 13-10-31](https://user-images.githubusercontent.com/2567162/63851707-e70a4c80-c996-11e9-95d4-30bf3a5c9ba4.png)

**Social app version:**
0.2.101

**Operating system**:
Clear Linux

**Web server:**
Official Docker Image

**Database:**
Official Docker Image

**PHP version:**
Official Docker Image

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

#### Nextcloud log (data/nextcloud.log)
it's empty

It's definitely problem with my configuration and reverse proxy.

**Comment by StCyr** [comment]
when I try to find your account from my social app, I get the following error:

`Aug 28 18:04:23 vps612142 Nextcloud[25743]: {no app in context} 500 - {"status":-1,"exception":"OCA\\Social\\Exceptions\\RequestNetworkException","message":"6 - Could not resolve host: www.version-originale.orgapps - {\"protocol\":\"http\",\"host\":\"localhost\",\"url\":\"\/apps\/social\/@kj\",\"timeout\":10,\"type\":0,\"data\":[]}"}`

Where www.version-originale.org is an alias of my nextcloud server.

Could it be that your setup has issues resolving hostnames?

**Comment by w84death** [comment]
Exactly. It forces localhost adress instead of domain. But I don't know what and where should I edit those settings.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by daita** [comment]
please send the result of:

```
./occ config:app:get social cloud_url
./occ config:app:get social social_url
./occ config:app:get social social_address
```

**Comment by w84death** [comment]
I see a problem and possible solution:

```
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social cloud_url
https://nextcloud.p1x.in
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social social_url
http://localhost:9777/apps/social/
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social social_address
www-data@ef58c4f646ad:~/html$
```

what exact values should I put there? 

https://nextcloud.p1x.in/apps/social/ for URL and what for address?

**Comment by daita** [comment]
`./occ social:reset` and fill with the right entries. After this. please send the result for the command from https://github.com/nextcloud/social/issues/707#issuecomment-526154530

**Comment by w84death** [comment]
```
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social social_url
https://nextcloud.p1x.in/apps/social/
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social cloud_url
https://nextcloud.p1x.in
www-data@ef58c4f646ad:~/html$ ./occ config:app:get social social_address
www-data@ef58c4f646ad:~/html$
```

It's working!
https://mastodon.social/web/accounts/893889
https://nextcloud.p1x.in/apps/social/@kj
At last something. I think I have problem with posting anything right now. But that's for separate investigation.

Thanks!
