### ISSUE TITLE
lock button on empty message

### ISSUE THREAD

**Issue by daita** [nextcloud/social#739]
If you enter a single chars in the Post field, the _Posting_ button turns enabled. Removing all content from the Post field should disable the button.

![issue_empty_message](https://user-images.githubusercontent.com/1038617/64955354-5386b600-d888-11e9-9cf8-7102e18d1a86.gif)

**Comment by StCyr** [comment]
should be fixed by https://github.com/nextcloud/social/pull/731

(commit 1e62feacb90518db04632f9d2afe7bfc13949b14)
