### ISSUE TITLE
Current account in Notification timeline

### ISSUE THREAD

**Issue by daita** [nextcloud/social#749]
Would be nice to display the current social account in the Notification timeline

**Comment by StCyr** [comment]
Do you mean the "ProfileInfo" component @daita?

(Profile with avatar, account name, tabs to show posts, followers, and following)?

**Comment by violoncelloCH** [comment]
I guess just the avatar and account name; it doesn't make sense to have posts and followers etc. there... just like fore the composer you see which user you are... but I'm not sure if this is really necessary at all; the avatar should already be visible at the top right... and you're not doing actions there where it would be necessary to know how your profile is appearing to others
what do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
Yeah, I don’t really think this is necessary either. The avatar is shown in the top right, you have a "Profile" section. And in the future, we could also have more details in the top right menu like display name and status.

**Comment by jancborchardt** [comment]
(Meaning, I’d say let’s close this. :)
