### ISSUE TITLE
Duplicate results on new mention

### ISSUE THREAD

**Issue by daita** [nextcloud/social#769]
When I write a new Post and start adding Mentions `@test1` I will have 2 results displayed. The one from the partial search, and the one from the exact search:

![Selection_108](https://user-images.githubusercontent.com/1038617/65870941-a6c73100-e37d-11e9-9b4a-76ae9e9aea27.png)
![Selection_109](https://user-images.githubusercontent.com/1038617/65870942-a6c73100-e37d-11e9-9840-7a025507c313.png)

**Comment by StCyr** [comment]
Fun fact: only local accounts have this problem

**Comment by StCyr** [comment]
probably linked: In "Profile" the followers and following lists also mention the account of the logged-in user.
