### ISSUE TITLE
Follow button shown on own-profile page when using host-meta

### ISSUE THREAD

**Issue by StCyr** [nextcloud/social#776]
**Describe the bug**
I've enabled host-meta to alias my domain "nextcloud.bollu.be" to "bollu.be".

Now, new users get an account in the form "<new_user>@bollu.be" rather than "<new_user@nextcloud.bollu.be". So far, so good.

The problem is that we use `cloudId` as identifier for the currently logged-in user at various places in the frontend. And, as a result, the currently logged-in user may not always be properly identified. 

Example, logged-in as user "testcyr123" and looking my profile page, the follow button is shown:

![image](https://user-images.githubusercontent.com/8179031/66054808-d79d9680-e534-11e9-87b0-e243ef0a7642.png)

**Expected behaviour**

The follow button shouldn't be shown when the currently logged-in user look at his own profile page.

**Comment by daita** [comment]
with #780 merged, it should be easier to check from the front-end the origin of the displayed Actor: check the value of the field 'viewerLink' in the returned JSON
