### ISSUE TITLE
on Nextcloud 17.0.0, i can't install social

### ISSUE THREAD

**Issue by Grosskopf** [nextcloud/social#804]
I updated to 17.0.0 with social installed (but not working quite correctly), then it didn't work, so i tried to remove it and reinstall, now when i try to install it, it sais:

> sudo -u www-data php occ app:install social
> Error: An exception occurred while executing 'SELECT COUNT(*) AS `count` FROM `oc_social_a2_follows` `f`':
> 
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_social_a2_follows' doesn't exist
> 

i installed social in 16.0.5, upgraded nextcloud to 17.0.0 and removed and reinstalled social

**Expected behavior**
When removing and reinstalling, the databases should reinitialize the tables if needed i believe

**Client details:**
i did this through ssh

<details>
<summary>Server details</summary>

**Social app version:**
0.2.101

**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx

**Database:**
Mariadb

**PHP version:**
7.3.9

**Nextcloud version:** (see Nextcloud admin page)

</details>
17.0.0
<details>
<summary>Logs</summary>

**Comment by Grosskopf** [comment]
just checked, there is no social stuff in my database after installing it

**Comment by Grosskopf** [comment]
same with master...

**Comment by StCyr** [comment]
Strange... maybe « ./occ config:app:set —value 0.2.100 social installed_version «  will fix this?

**Comment by Grosskopf** [comment]
oh, it seems like the error, changed, now it is                                       
" There is no table with name 'nextcloud.oc_social_a2_stream_action' in the schema. "

**Comment by StCyr** [comment]
Maybe you should try with version equal to 0, like:

« occ config:app:set —value 0.0.000 social installed_version »

@daita, any idea how to help this guy construct his social tables?

Cyrille

**Comment by Grosskopf** [comment]
oh i forgot to comment, setting the value to any of those two doesn't help with the issue currently, it doesn't even change the error message to those sream_action things anymore, i've installed build dependencies between trying though

**Comment by Grosskopf** [comment]
oh i found something in the npm-debug log:

> 17 error Linux 4.15.0-43-generic
> 18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
> 19 error node v8.10.0
> 20 error npm  v3.5.2
> 21 error code ELIFECYCLE
> 22 error social@0.0.1 test: `jest`
> 22 error Exit status 1
> 23 error Failed at the social@0.0.1 test script 'jest'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the social package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     jest
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs social
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls social
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> 
>

**Comment by StCyr** [comment]
> 22 error social@0.0.1 test: `jest`

There's no unit testing currently (you're welcome to implement this if you can :-))

**Comment by Grosskopf** [comment]
ah ok, that npm is not my version :D damn, i thought i would have found something :D

**Comment by StCyr** [comment]
hey, 

apparently `Occ social:reset --uninstall` should solve your issue

**Comment by Grosskopf** [comment]
thanks :) sadly i cannot call occ social:reset.. it throws this:                                                             
  There are no commands defined in the "social" namespace.

**Comment by Grosskopf** [comment]
using 

> occ config:app:set --value yes social enabled

i got it to unlock that command

but flushing data fails on

> occ social:reset --uninstall  

with:

> Do you confirm this operation? (y/N) y
> Operation is destructive. Are you sure about this? (y/N) y
> 
> flushing data... fail
>

**Comment by Grosskopf** [comment]
i have something like this all the time:

>{"reqId":"YJFVCcdTaHRI3NKATH0F","level":1,"time":"2019-11-05T15:43:38+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs occ in global mode","userAgent":"--","version":"17.0.0.9"}
> {"reqId":"iDbphDsTdtXZr4JEydiF","level":1,"time":"2019-11-05T15:45:49+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"17.0.0.9"}
> {"reqId":"iDbphDsTdtXZr4JEydiF","level":1,"time":"2019-11-05T15:45:49+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"17.0.0.9"}

and then this huge bit about the missing tables in social from core, but that is a timed process, i believe you mean the cli thing, right?
I have no idea what all this means :/ i have a weird  VServer at Strato though, i hope this is not an issue, don't have seccomp or virtualization stuff in kernel

**Comment by Grosskopf** [comment]
i just switched to nextcloud 17.0.1 and got the error, but now i know the file where it's coming from :D

in lib/Db/FollowsRequest.php line 160 nextcloud.oc_social_a2_follows doesn't exist

a quick look at master told me stuff changed there.
in master it is "there is no table with name 'nextcloud.oc_social_a2_stream_action" coming from lib/Migration/Version0002Date20190925000001.php line 77

**Comment by Grosskopf** [comment]
changing "EmptyAll()" in lib/Command/Reset.php to "uninstallSocialTables()" line 120 i think is surposed to do the same and works for the `occ social:reset --uninstall` thing in my case because it tests if the table exists before removing it, now upon trying to enable i get:
 

> General error: 1813 Tablespace for table '`nextcloud`.`oc_social_a2_actors`' exists. Please DISCARD the tablespace before IMPORT.

to discard those i used `rm /var/lib/mysql/nextcloud/oc_social_a2*`

maybe that was unnecessary, it didn't help too much, i then removed the social app and reenabled social, now it works

**Comment by Grosskopf** [comment]
maybe it just broke my database completely xD will try to migrate my database

**Comment by Grosskopf** [comment]
and the last issue is resolved, i forgot a / at the social url, it was
`https://nextcloud.url.com/apps/social`
and had to be:
`https://nextcloud.url.com/apps/social/`

since the other thing seems to be far upstream, i'll close this issue for now
