### ISSUE TITLE
Nextcloud does not seem to work with ActivityPub clients like Roma

### ISSUE THREAD

**Issue by apcameron** [nextcloud/social#834]
When I try to log on it fails with the following entry in the Nextcloud logs
 "POST /api/v1/apps HTTP/1.1" 404 282

**Comment by spaetz** [comment]
These clients use the Mastodon API which is not implemented in Nextcloud social as it is strictly speaking not part of ActivityPub. There is an issue about this #145.

**Comment by violoncelloCH** [comment]
yes, as @spaetz said... closing this as a duplicate of #145
