### ISSUE TITLE
I need to know how to delete my nextcloud account?

### ISSUE THREAD

**Issue by lalascott7** [nextcloud/social#842]
Hello,
I am no longer using my NextCloud account with the storage. I do not see anywhere where to delete my account. Can you please just delete it? I found another encrypt file storage solution. It is very frustrating to see nowhere you can just hit delete account and you guys should have something like that for users. Thanks

**Comment by violoncelloCH** [comment]
Hi @lalascott7 
Please note, that Nextcloud itself is just the software, but not the service provider; Nextcloud is the code that runs at whatever service provider you have signed up to. Please contact your service provider to ask them to delete your account.

**Comment by lalascott7** [comment]
Hello. 
Service provider? What do you mean? Do you mean my ISP? To me this doesn't make any sense. If I signed up to your service, you guys should just delete my account. Otherwise it will just be there unused. 

--
Best Regards,

 LaToya Scott
 lalascott@postinbox.com

....
Are you a health and wellness entrepreneur that needs an extra helping hand with managing your website, setting up your social media, or handling your endless to-do list of tasks? Or are you looking to start a business? Get a free assessment at linktr.ee/lsvirtualconsulting for more information. Let us help you save time, increase your productivity and grow your your business, virtually.

**Comment by violoncelloCH** [comment]
Where did you log in to your account? Could you paste the URL to the login?
