### ISSUE TITLE
Add notifications stream

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/social#85]
From #34 

- [ ] **🔔 Notifications:** @mentions, new followers, people liking or reposting your posts or things you were mentioned in, you being tagged in pictures etc. ("Activity" as word for this is easy to misunderstand as it’s less specific)

**Comment by daita** [comment]
@juliushaertl would be nice to have a first version of the stream including at least the @mention for 0.1.1. For the like/repost/following you, we'll see that later

**Comment by StCyr** [comment]
would be fixed by https://github.com/nextcloud/social/pull/625
