### ISSUE TITLE
Primary index name on "oc_social_a2_cache_documts" is too long.

### ISSUE THREAD

**Issue by reavessm** [nextcloud/social#850]
**Describe the bug**
 App can not be installed on NC 18.0.0.9 as a error during db-migration occurs.  Seems related to #506 

**To Reproduce**

    1. Go to Social on the Apps-Page of your nextcloud instance
    1. Click on 'Download and enable'
    1. Error message Primary index name on "oc_social_a2_cache_documts" is too long.
    1. App is not installed.

**Expected behavior**
App is installed correctly with needed db

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 72.01
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version**:
0.2.101?

**Operating system**:
Debian (Docker)

**Web server:**
Apache 2.4.38

**Database:**
Sqlite3 3.27.2

**PHP version:**
7.3.13

**Nextcloud version:** 
18.0.0 RC2
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[settings] Error: InvalidArgumentException: Primary index name  on "oc_social_a2_cache_documts" is too long. at <<closure>>

 0. /var/www/html/lib/private/DB/MigrationService.php line 484
    OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)
 1. /var/www/html/lib/private/DB/MigrationService.php line 414
    OC\DB\MigrationService->executeStep("0002Date20190506000001", false)
 2. /var/www/html/lib/private/Installer.php line 151
    OC\DB\MigrationService->migrate()
 3. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 443
    OC\Installer->installApp("social")
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["social"], [])
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 6. /var/www/html/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
 9. /var/www/html/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
10. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/enable")
11. /var/www/html/index.php line 38
    OC::handleRequest()

POST /settings/apps/enable
```

#### Browser log
```
Insert your browser log here, this could for example include:

Object { apps: Getter & Setter, categories: Getter & Setter, updateCount: Getter & Setter, loading: Getter & Setter, loadingList: Getter & Setter, … }
 
{…}
​
appId: "social"
​
error: Error
​​
columnNumber: 81448
​​
config: Object { url: "/settings/apps/enable", method: "post", data: "{\"appIds\":[\"social\"],\"groups\":[]}", … }
​​
fileName: "https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5"
​​
isAxiosError: true
​​
lineNumber: 7
​​
message: "Request failed with status code 500"
​​
request: XMLHttpRequest
​​​
mozAnon: false
​​​
mozSystem: false
​​​
onabort: function onabort()
​​​
onerror: function onerror()
​​​
onload: null
​​​
onloadend: null
​​​
onloadstart: null
​​​
onprogress: null
​​​
onreadystatechange: function onreadystatechange()
​​​
ontimeout: function ontimeout()
​​​
readyState: 4
​​​
response: "{\"data\":{\"message\":\"Primary index name  on \\\"oc_social_a2_cache_documts\\\" is too long.\"}}"
​​​
responseText: "{\"data\":{\"message\":\"Primary index name  on \\\"oc_social_a2_cache_documts\\\" is too long.\"}}"
​​​
responseType: ""
​​​
responseURL: "https://nextcloud.domain.com/settings/apps/enable"
​​​
responseXML: null
​​​
status: 500
​​​
statusText: "Internal Server Error"
​​​
timeout: 0
​​​
upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
​​​
withCredentials: false
​​​
<prototype>: XMLHttpRequestPrototype { open: open(), setRequestHeader: setRequestHeader(), send: send(), … }
​​
response: {…}
​​​
config: Object { url: "/settings/apps/enable", method: "post", data: "{\"appIds\":[\"social\"],\"groups\":[]}", … }
​​​
data: Object { data: {…} }
​​​
headers: Object { "cache-control": "no-cache, no-store, must-revalidate", "content-length": "89", "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self'", … }
​​​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​​
status: 500
​​​
statusText: "Internal Server Error"
​​​
<prototype>: Object { … }
​​
stack: "t.exports@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:7:81448\nt.exports@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:45:2592\nt.exports/</p.onreadystatechange@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:7:80381\n"
​​
toJSON: function toJSON()
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
apps.js:38:10

```

</details>

**Comment by guenterzimmermann** [comment]
For NC 18.0.0.10 it is the same.

**Comment by amiga23** [comment]
Same for me with latest 18 docker image and latest MariaDB. The maximum index length is 64 characters according to this documentation: https://mariadb.com/kb/en/identifier-names/#maximum-length

**Comment by amiga23** [comment]
Same for me with latest 18 docker image and latest MariaDB. The maximum index length is 64 characters according to this documentation: https://mariadb.com/kb/en/identifier-names/#maximum-length

**Comment by OtisPresley** [comment]
Same for me on the Docker Apache 18 image.

**Comment by granfot** [comment]
Also true for 18.0.0.0

**Comment by reavessm** [comment]
Any update on this?

**Comment by Stopka** [comment]
+1 on 18.0.1 Docker with MariaDb

**Comment by batgranny** [comment]
+1 on 18.0.1 on MySQL

**Comment by rubo77** [comment]
Can't you just set up the max character limit for the index keys in mariaDB somehow?

**Comment by stauffenbits** [comment]
Could we decrease the table name size for this plugin until this is fixed?

**Comment by rubo77** [comment]
I could create a pr, but I didn't find the place in the code, where the database is created.

Any hints?

**Comment by rubo77** [comment]
Where do I find the table definition?

**Comment by rubo77** [comment]
It seems like there is no table definition, It is just the result of all Migration steps, starting with `lib/Migration/Version0002Date20190506000001.php` which creates the new tables.

I'll try adding a Migration step using this function:

https://github.com/nextcloud/3rdparty/blob/d183b9cbdc62f2302f34cdf51f92aa45a1bb9f60/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php#L330

But I am afraid, the error already occurs in the first step, where the cache table is created. am I right?

**Comment by rubo77** [comment]
I found a workaround, but it seems like the tables `social_a2_request_queue` and `social_a2_stream_action` are too long also 

## workaround:

```
grep -rl social_a2_cache_documts custom_apps/social/| xargs sed -i s/social_a2_cache_documts/social_a2_cache_docum/g
grep -rl social_a2_request_queue custom_apps/social/| xargs sed -i s/social_a2_request_queue/social_a2_request_q/g
grep -rl social_a2_stream_action custom_apps/social/| xargs sed -i s/social_a2_stream_action/social_a2_stream_act/g

Go into your nextcloud directory and rename the tables in all files

**Comment by stauffenbits** [comment]
I can confirm that rubo77's workaround will allow social to be installed. 

Unfortunately, I now get a ".well-known/webfinger isn't properly set up!". Should I open a separate bug report for that?

**Comment by julianborghuis** [comment]
whwen is this fixed ;(

**Comment by ivanincanada** [comment]
> I can confirm that rubo77's workaround will allow social to be installed.
> 
> The only thing I had to change was `custom_apps` to `apps`.
> 
> Unfortunately, I now get a ".well-known/webfinger isn't properly set up!". Should I open a separate bug report for that?

double confirmed. 

I have been fighting with this for days and had resorted to digging to code, but thought to check here first - then I saw this. I had removed the limitation from the Database though - but that required a fix to MariaDB, in any case, this was the better fix. so i applied it, and worked first time. 


if you are migrating from an old version of nextcloud with social enabled already, it 'seems' to work but later down the line seems to have issues with autodiscovery (but maybe that's my setup) - however, that went away also once i removed the app (after the upgrade to latest) and reinstalled after applying the fix above. 

for me, i went straight to the app/social folder, adjusted his three commands to point to ./ and immediatly my 4 production sites (applying the same fix to all as they are running) fixed it for me. 

so THANK you for that fix!

**Comment by ivanincanada** [comment]
> Unfortunately, I now get a ".well-known/webfinger isn't properly set up!". Should I open a separate bug report for that?

Unfortunately, I now get a ".well-known/webfinger isn't properly set up!". Should I open a separate bug report for that?

look into your autoconfigure or proxy settings on nginx

Look into - Nextcloud - Autoconfigure for WebCal etc documentation - while enabling autoconfigure - there similar settings required I believe for web finger to work, but not sure if fix is related, as a note, my webfinger issue (as I forced the social install by manually adjusting shit in the db etc and moving files about, removing checks and adding some redirection inside of social itself) at one stage appeared to be working, but was also throwing the webfinger issue - but it went away after applying the fix above - but previously in my troubleshooting I had gone back and noticed I had not configured autoconfigure correctly and had to play with some nginx settings (on plesk) to get social to see my 'domain name' and not 'localhost' - it was due to a misconfiguration or incomplete configuration on my part, the issue might be just down to similar on yours.

**Comment by profzelonka** [comment]
> 
> 
> I found a workaround, but it seems like the tables `social_a2_request_queue` and `social_a2_stream_action` are too long also
> ## workaround:
> 
> Go into your nextcloud directory and rename the tables in all files with sed:
> 
> ```
> grep -rl social_a2_cache_documts custom_apps/social/| xargs sed -i s/social_a2_cache_documts/social_a2_cache_docum/g
> grep -rl social_a2_request_queue custom_apps/social/| xargs sed -i s/social_a2_request_queue/social_a2_req_queue/g
> grep -rl social_a2_stream_action custom_apps/social/| xargs sed -i s/social_a2_stream_action/social_a2_stream_act/g
> ```
> 
> I added those changes in a PR ...

All three fail...

> root@nextcloud:/usr/local/www/nextcloud # grep -rl social_a2_cache_documts apps/social/ | xargs sed -i s/social_a2_cache_documts/social_a2_cache_docum/g
> sed: 1: "apps/social/lib/Db/Core ...": command a expects \ followed by text

**Comment by rubo77** [comment]
> had removed the limitation from the Database

How did you do that?

**Comment by kamilr** [comment]
Maybe I did sth wrong but after fix I have an error after enable plugin:

> An exception occurred while executing 'ALTER TABLE oc_social_a2_stream_act ADD COLUMN liked BOOLEAN NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

SW: nextcloud:stable-fpm 18.0.3 & SQLite

**Comment by ivanincanada** [comment]
I had to rebuild and rejig mariadb under the hood. It was a hack. Not a fix

**Comment by rubo77** [comment]
Who is gonna check #879 which would fix this?

**Comment by kamilr** [comment]
> Maybe I did sth wrong but after fix I have an error after enable plugin:
> 
> > An exception occurred while executing 'ALTER TABLE oc_social_a2_stream_act ADD COLUMN liked BOOLEAN NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
> 
> SW: nextcloud:stable-fpm 18.0.3 & SQLite

On MariaDB-1:10.4.12+maria~bionic it works!

**Comment by ivanincanada** [comment]
> Unfortunately, the content of Social tab/app is empty.

have you checked that you 'post' content to a channel that has people to 'view it'. if you post as non public and you have no other accounts to view it the post doesn't seem to get posted. i had to post public to test and then set up some test contacts before i got social to target and view stuff correctly. it first appeared when i posted nothing happened but once i had contacts (besides a solo admin) it worked fine. might not be the case but double check that yourself. it might actually be working

**Comment by kaleb** [comment]
I don't know if this is helpful information or not. The install works with postgres but not with Maria DB.

**Comment by profzelonka** [comment]
> 
> 
> I don't know if this is helpful information or not. The install works with postgres but not with Maria DB.

Can confirm, not working with Maria DB. :(

**Comment by kaleb** [comment]
The problem here is that you have dbtableprefix set to "oc_" in your nextcloud config.

**Comment by djdomi** [comment]
> The problem here is that you have dbtableprefix set to "oc_" in your nextcloud config.
The Problem is either, that maria db is limited on string name length. So far it is a valid bug and needs to be changed.

- [ ] Request for Change table Name

Affected files: (18.03&18.04)
[cloud.patch.txt](https://github.com/nextcloud/social/files/4585991/cloud.patch.txt)


- [ ] change: apps/social/lib/Db/CoreRequestBuilder.php
- [ ] change: apps/social/lib/Migration/Version0002Date20190506000001.php
- [ ] change: apps/social/lib/Migration/Version0002Date20190622000001.php
- [ ] change: apps/social/lib/Migration/Version0002Date20190717000001.php


i submit a patch to fix this

**Comment by rubo77** [comment]
@djdomi I already created a PR: https://github.com/nextcloud/social/pull/879

I think we also have to change the migration steps, otherwise it crashes there. I did that in my PR, but maybe we have to enhance it, so NC instances, that are already working with the long table-names need a table-rename Migration in the right place, before the ordinary Migration begins

**Comment by rubo77** [comment]
> The problem here is that you have dbtableprefix set to "oc_" in your nextcloud config.

So another **workaround** would be to reinstall nextcloud without `oc_` as EXTCLOUD_TABLE_PREFIX

I tried this in my docker-test-install, but it seems, like it is [impossible to install the docker Nextcloud without `oc_` as prefix](https://github.com/nextcloud/docker/issues/776)

**Comment by rubo77** [comment]
> The problem here is that you have dbtableprefix set to "oc_" in your nextcloud config.

No, I tried this, I removed the "oc_" prefix from all my tables and edited config.php but then I get the same according error:

    Primary index name on "social_a2_cache_documts" is too long.

so removing the prefix is not enough!

**Comment by Windyo** [comment]
Trying to install social after an `occ:social reset --uninstall` still yields `Primary index name on "oc_social_a2_cache_documts" is too long.` when installing via app store on NC19 - doesn't seem closed on my side

**Comment by djdomi** [comment]
> Trying to install social after an `occ:social reset --uninstall` still yields `Primary index name on "oc_social_a2_cache_documts" is too long.` when installing via app store on NC19 - doesn't seem closed on my side

my merge request was denied, as it would rename documts to doc which would fix this issue

**Comment by daita** [comment]
alpha3 should be released later today.
