### ISSUE TITLE
Make Social account creation optional

### ISSUE THREAD

**Issue by rodneyrod** [nextcloud/social#862]
**Is your feature request related to a problem? Please describe.**
Currently all users on a Nextcloud instance will have a Social account created for them if they go into the Social panel, and there is no way to restrict this.

**Describe the solution you'd like**
Have a dialog in Settings where you can opt-in or opt-out users to have access to Social.

**Describe alternatives you've considered**
Just trying not to click on the Social button, hasn't always worked

**Comment by violoncelloCH** [comment]
have you considered restricting the app to (a) certain group(s)? (you can do this directly from within the app store) (checkbox next to "disable" social)
this disables and hides the app completely for other users...

**Comment by rodneyrod** [comment]
Thanks for the suggestion, it's working so I'll close off this request.
