### ISSUE TITLE
Shortcut in user menu to follow on Social

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#87]
Just like we have shortcuts to mail a person and Talk to a person via the user menu when you click on their name/avatar, we should have something like "Follow on Social":
![follow on social](https://user-images.githubusercontent.com/925062/49327970-ce384c00-f568-11e8-86f8-61db1ef7dc5f.png)
Same for the Contacts menu in the header where the actions are listed too. Once you follow a person, it could switch from "Follow `First name` on Social" to "Posts on Social".

This would be great already for first alpha too because it’s nice integration with the rest of Nextcloud. Is that possible @juliushaertl @georgehrke @ChristophWurst? :)

**Comment by daita** [comment]
https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml#L104-L106

**Comment by daita** [comment]
implemented
