### ISSUE TITLE
Fedilab error: "Unable to get client id!"

### ISSUE THREAD

**Issue by binerf** [nextcloud/social#875]
**Describe the bug**
Facing an issue when trying to configure Android Fedilab app to connect my Nextcloud Social instance.
Error message: "Unable to get client id!"

**To Reproduce**
1. Start Fedilab Android App
2. Create new account
3. Type instance URL
4. Click on "Connect"

**Expected behavior**
New page on Fedilab app to enter Login and Password

**Screenshots**

**Client details:**
 - OS: Android
 - Browser N/A
 - Version 2.30.0 (Fedilab app)
 - Device: Android equipment

<details>
<summary>Server details</summary>

**Social app version:**
0.2.101 (Social App)

**Operating system**:
Ubuntu

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
php 7.2
**Nextcloud version:** (see Nextcloud admin page)

</details>

**Comment by mediaformat** [comment]
#145

**Comment by violoncelloCH** [comment]
This is not possible yet, but a planned feature... See #145 - closing this as a duplicate
