### ISSUE TITLE
"Skipping optional dependency" in make dev-setup

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/social#90]
It’s not critical, but it would be nice to have no scary-looking warnings at all in any of the setup steps:
```
~/nextcloud/apps/social$ make dev-setup 
rm -f js/social.js
rm -f js/social.js.map
rm -rf node_modules
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Could we get rid of those `npm WARN` lines? @juliushaertl

**Comment by juliushaertl** [comment]
There is not much we can do about that, since fsevents is an optional dependency that is pulled in by jest, which is only available (and needed) when running on mac os.
